// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/clock/clock.proto

package clock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetClockDemand struct {
	Time                 uint64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	CycleDuration        uint64   `protobuf:"varint,2,opt,name=cycle_duration,json=cycleDuration,proto3" json:"cycle_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetClockDemand) Reset()         { *m = SetClockDemand{} }
func (m *SetClockDemand) String() string { return proto.CompactTextString(m) }
func (*SetClockDemand) ProtoMessage()    {}
func (*SetClockDemand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{0}
}

func (m *SetClockDemand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClockDemand.Unmarshal(m, b)
}
func (m *SetClockDemand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClockDemand.Marshal(b, m, deterministic)
}
func (m *SetClockDemand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClockDemand.Merge(m, src)
}
func (m *SetClockDemand) XXX_Size() int {
	return xxx_messageInfo_SetClockDemand.Size(m)
}
func (m *SetClockDemand) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClockDemand.DiscardUnknown(m)
}

var xxx_messageInfo_SetClockDemand proto.InternalMessageInfo

func (m *SetClockDemand) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SetClockDemand) GetCycleDuration() uint64 {
	if m != nil {
		return m.CycleDuration
	}
	return 0
}

type SetClockSupply struct {
	ClockInfo            *ClockInfo `protobuf:"bytes,1,opt,name=clock_info,json=clockInfo,proto3" json:"clock_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetClockSupply) Reset()         { *m = SetClockSupply{} }
func (m *SetClockSupply) String() string { return proto.CompactTextString(m) }
func (*SetClockSupply) ProtoMessage()    {}
func (*SetClockSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{1}
}

func (m *SetClockSupply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClockSupply.Unmarshal(m, b)
}
func (m *SetClockSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClockSupply.Marshal(b, m, deterministic)
}
func (m *SetClockSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClockSupply.Merge(m, src)
}
func (m *SetClockSupply) XXX_Size() int {
	return xxx_messageInfo_SetClockSupply.Size(m)
}
func (m *SetClockSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClockSupply.DiscardUnknown(m)
}

var xxx_messageInfo_SetClockSupply proto.InternalMessageInfo

func (m *SetClockSupply) GetClockInfo() *ClockInfo {
	if m != nil {
		return m.ClockInfo
	}
	return nil
}

type ForwardClockDemand struct {
	Time                 uint64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	CycleNum             uint64   `protobuf:"varint,2,opt,name=cycle_num,json=cycleNum,proto3" json:"cycle_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockDemand) Reset()         { *m = ForwardClockDemand{} }
func (m *ForwardClockDemand) String() string { return proto.CompactTextString(m) }
func (*ForwardClockDemand) ProtoMessage()    {}
func (*ForwardClockDemand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{2}
}

func (m *ForwardClockDemand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockDemand.Unmarshal(m, b)
}
func (m *ForwardClockDemand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockDemand.Marshal(b, m, deterministic)
}
func (m *ForwardClockDemand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockDemand.Merge(m, src)
}
func (m *ForwardClockDemand) XXX_Size() int {
	return xxx_messageInfo_ForwardClockDemand.Size(m)
}
func (m *ForwardClockDemand) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockDemand.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockDemand proto.InternalMessageInfo

func (m *ForwardClockDemand) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ForwardClockDemand) GetCycleNum() uint64 {
	if m != nil {
		return m.CycleNum
	}
	return 0
}

type ForwardClockSupply struct {
	ClockInfo            *ClockInfo `protobuf:"bytes,1,opt,name=clock_info,json=clockInfo,proto3" json:"clock_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ForwardClockSupply) Reset()         { *m = ForwardClockSupply{} }
func (m *ForwardClockSupply) String() string { return proto.CompactTextString(m) }
func (*ForwardClockSupply) ProtoMessage()    {}
func (*ForwardClockSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{3}
}

func (m *ForwardClockSupply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockSupply.Unmarshal(m, b)
}
func (m *ForwardClockSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockSupply.Marshal(b, m, deterministic)
}
func (m *ForwardClockSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockSupply.Merge(m, src)
}
func (m *ForwardClockSupply) XXX_Size() int {
	return xxx_messageInfo_ForwardClockSupply.Size(m)
}
func (m *ForwardClockSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockSupply.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockSupply proto.InternalMessageInfo

func (m *ForwardClockSupply) GetClockInfo() *ClockInfo {
	if m != nil {
		return m.ClockInfo
	}
	return nil
}

type BackClockDemand struct {
	Time                 uint64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	CycleNum             uint64   `protobuf:"varint,2,opt,name=cycle_num,json=cycleNum,proto3" json:"cycle_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackClockDemand) Reset()         { *m = BackClockDemand{} }
func (m *BackClockDemand) String() string { return proto.CompactTextString(m) }
func (*BackClockDemand) ProtoMessage()    {}
func (*BackClockDemand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{4}
}

func (m *BackClockDemand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackClockDemand.Unmarshal(m, b)
}
func (m *BackClockDemand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackClockDemand.Marshal(b, m, deterministic)
}
func (m *BackClockDemand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackClockDemand.Merge(m, src)
}
func (m *BackClockDemand) XXX_Size() int {
	return xxx_messageInfo_BackClockDemand.Size(m)
}
func (m *BackClockDemand) XXX_DiscardUnknown() {
	xxx_messageInfo_BackClockDemand.DiscardUnknown(m)
}

var xxx_messageInfo_BackClockDemand proto.InternalMessageInfo

func (m *BackClockDemand) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BackClockDemand) GetCycleNum() uint64 {
	if m != nil {
		return m.CycleNum
	}
	return 0
}

type BackClockSupply struct {
	ClockInfo            *ClockInfo `protobuf:"bytes,1,opt,name=clock_info,json=clockInfo,proto3" json:"clock_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BackClockSupply) Reset()         { *m = BackClockSupply{} }
func (m *BackClockSupply) String() string { return proto.CompactTextString(m) }
func (*BackClockSupply) ProtoMessage()    {}
func (*BackClockSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{5}
}

func (m *BackClockSupply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackClockSupply.Unmarshal(m, b)
}
func (m *BackClockSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackClockSupply.Marshal(b, m, deterministic)
}
func (m *BackClockSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackClockSupply.Merge(m, src)
}
func (m *BackClockSupply) XXX_Size() int {
	return xxx_messageInfo_BackClockSupply.Size(m)
}
func (m *BackClockSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_BackClockSupply.DiscardUnknown(m)
}

var xxx_messageInfo_BackClockSupply proto.InternalMessageInfo

func (m *BackClockSupply) GetClockInfo() *ClockInfo {
	if m != nil {
		return m.ClockInfo
	}
	return nil
}

type ClockInfo struct {
	Time                 uint64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	CycleNum             uint64   `protobuf:"varint,2,opt,name=cycle_num,json=cycleNum,proto3" json:"cycle_num,omitempty"`
	CycleDuration        uint64   `protobuf:"varint,3,opt,name=cycle_duration,json=cycleDuration,proto3" json:"cycle_duration,omitempty"`
	CycleInterval        uint64   `protobuf:"varint,4,opt,name=cycle_interval,json=cycleInterval,proto3" json:"cycle_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockInfo) Reset()         { *m = ClockInfo{} }
func (m *ClockInfo) String() string { return proto.CompactTextString(m) }
func (*ClockInfo) ProtoMessage()    {}
func (*ClockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{6}
}

func (m *ClockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockInfo.Unmarshal(m, b)
}
func (m *ClockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockInfo.Marshal(b, m, deterministic)
}
func (m *ClockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockInfo.Merge(m, src)
}
func (m *ClockInfo) XXX_Size() int {
	return xxx_messageInfo_ClockInfo.Size(m)
}
func (m *ClockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClockInfo proto.InternalMessageInfo

func (m *ClockInfo) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ClockInfo) GetCycleNum() uint64 {
	if m != nil {
		return m.CycleNum
	}
	return 0
}

func (m *ClockInfo) GetCycleDuration() uint64 {
	if m != nil {
		return m.CycleDuration
	}
	return 0
}

func (m *ClockInfo) GetCycleInterval() uint64 {
	if m != nil {
		return m.CycleInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*SetClockDemand)(nil), "api.clock.SetClockDemand")
	proto.RegisterType((*SetClockSupply)(nil), "api.clock.SetClockSupply")
	proto.RegisterType((*ForwardClockDemand)(nil), "api.clock.ForwardClockDemand")
	proto.RegisterType((*ForwardClockSupply)(nil), "api.clock.ForwardClockSupply")
	proto.RegisterType((*BackClockDemand)(nil), "api.clock.BackClockDemand")
	proto.RegisterType((*BackClockSupply)(nil), "api.clock.BackClockSupply")
	proto.RegisterType((*ClockInfo)(nil), "api.clock.ClockInfo")
}

func init() { proto.RegisterFile("simulation/clock/clock.proto", fileDescriptor_e96fed1976809896) }

var fileDescriptor_e96fed1976809896 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x06, 0x31, 0x2b, 0x56, 0x58, 0x3c, 0x04, 0xf4, 0x20, 0x01, 0xc1, 0xd3, 0x06,
	0x2c, 0xe2, 0x3d, 0xb6, 0x85, 0x20, 0x78, 0x68, 0x6f, 0x5e, 0xc2, 0x76, 0xb3, 0xb5, 0x4b, 0xf7,
	0x1f, 0xdb, 0x5d, 0x35, 0x5f, 0xc1, 0x4f, 0x2d, 0x4e, 0xd3, 0x3f, 0x4a, 0x41, 0x4a, 0x2e, 0xbb,
	0xc3, 0x9b, 0xc7, 0x9b, 0x1f, 0xcc, 0xa0, 0xeb, 0xa5, 0x50, 0x41, 0x52, 0x2f, 0x8c, 0xce, 0x99,
	0x34, 0x6c, 0xb1, 0x7a, 0x89, 0x75, 0xc6, 0x1b, 0x9c, 0x50, 0x2b, 0x08, 0x08, 0xd9, 0x33, 0xea,
	0x4d, 0xb8, 0x7f, 0xfa, 0xa9, 0x07, 0x5c, 0x51, 0x5d, 0x63, 0x8c, 0x62, 0x2f, 0x14, 0x4f, 0xa3,
	0x9b, 0xe8, 0x2e, 0x1e, 0x43, 0x8d, 0x6f, 0x51, 0x8f, 0x35, 0x4c, 0xf2, 0xaa, 0x0e, 0x0e, 0x42,
	0xd3, 0x23, 0xe8, 0x9e, 0x83, 0x3a, 0x68, 0xc5, 0x6c, 0xb8, 0x0d, 0x9b, 0x04, 0x6b, 0x65, 0x83,
	0xfb, 0x08, 0xc1, 0x9c, 0x4a, 0xe8, 0x99, 0x81, 0xc8, 0xb3, 0xfb, 0x4b, 0xb2, 0x19, 0x4f, 0xc0,
	0x5b, 0xea, 0x99, 0x19, 0x27, 0x6c, 0x5d, 0x66, 0x43, 0x84, 0x47, 0xc6, 0x7d, 0x50, 0x57, 0xff,
	0xc7, 0x75, 0x85, 0x92, 0x15, 0x97, 0x0e, 0xaa, 0x45, 0x3a, 0x05, 0xe1, 0x25, 0xa8, 0xac, 0xfc,
	0x1d, 0xd3, 0x85, 0xa8, 0x40, 0x17, 0x05, 0x65, 0x8b, 0x4e, 0x38, 0xa3, 0x9d, 0x8c, 0x2e, 0x2c,
	0x5f, 0x11, 0x4a, 0x36, 0x8d, 0x83, 0x31, 0xf6, 0xac, 0xf2, 0x78, 0xcf, 0x2a, 0xb7, 0x36, 0xa1,
	0x3d, 0x77, 0xef, 0x54, 0xa6, 0xf1, 0x8e, 0xad, 0x6c, 0xc5, 0xe2, 0xf1, 0xf5, 0xe1, 0x4d, 0xf8,
	0x79, 0x98, 0x12, 0x66, 0x54, 0xbe, 0x6c, 0x34, 0x77, 0xfc, 0x73, 0xfd, 0x57, 0x54, 0xda, 0x39,
	0xcd, 0xa9, 0x15, 0xf9, 0xdf, 0x73, 0x9c, 0x9e, 0xc0, 0x25, 0xf6, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xa1, 0x54, 0x7a, 0x29, 0xa9, 0x02, 0x00, 0x00,
}
