// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/clock/clock.proto

package clock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusType int32

const (
	StatusType_OK   StatusType = 0
	StatusType_NG   StatusType = 1
	StatusType_NONE StatusType = 2
)

var StatusType_name = map[int32]string{
	0: "OK",
	1: "NG",
	2: "NONE",
}

var StatusType_value = map[string]int32{
	"OK":   0,
	"NG":   1,
	"NONE": 2,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{0}
}

type ClockType int32

const (
	ClockType_FORWARD ClockType = 0
	ClockType_BACK    ClockType = 1
	ClockType_SET     ClockType = 2
	ClockType_START   ClockType = 3
	ClockType_STOP    ClockType = 4
)

var ClockType_name = map[int32]string{
	0: "FORWARD",
	1: "BACK",
	2: "SET",
	3: "START",
	4: "STOP",
}

var ClockType_value = map[string]int32{
	"FORWARD": 0,
	"BACK":    1,
	"SET":     2,
	"START":   3,
	"STOP":    4,
}

func (x ClockType) String() string {
	return proto.EnumName(ClockType_name, int32(x))
}

func (ClockType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{1}
}

type ClockService struct {
	// Types that are valid to be assigned to ClockServiceAction:
	//	*ClockService_ClockInfo_
	//	*ClockService_ClockRequest_
	ClockServiceAction   isClockService_ClockServiceAction `protobuf_oneof:"ClockServiceAction"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ClockService) Reset()         { *m = ClockService{} }
func (m *ClockService) String() string { return proto.CompactTextString(m) }
func (*ClockService) ProtoMessage()    {}
func (*ClockService) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{0}
}

func (m *ClockService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockService.Unmarshal(m, b)
}
func (m *ClockService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockService.Marshal(b, m, deterministic)
}
func (m *ClockService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockService.Merge(m, src)
}
func (m *ClockService) XXX_Size() int {
	return xxx_messageInfo_ClockService.Size(m)
}
func (m *ClockService) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockService.DiscardUnknown(m)
}

var xxx_messageInfo_ClockService proto.InternalMessageInfo

type isClockService_ClockServiceAction interface {
	isClockService_ClockServiceAction()
}

type ClockService_ClockInfo_ struct {
	ClockInfo *ClockService_ClockInfo `protobuf:"bytes,1,opt,name=clock_info,json=clockInfo,proto3,oneof"`
}

type ClockService_ClockRequest_ struct {
	ClockRequest *ClockService_ClockRequest `protobuf:"bytes,2,opt,name=clock_request,json=clockRequest,proto3,oneof"`
}

func (*ClockService_ClockInfo_) isClockService_ClockServiceAction() {}

func (*ClockService_ClockRequest_) isClockService_ClockServiceAction() {}

func (m *ClockService) GetClockServiceAction() isClockService_ClockServiceAction {
	if m != nil {
		return m.ClockServiceAction
	}
	return nil
}

func (m *ClockService) GetClockInfo() *ClockService_ClockInfo {
	if x, ok := m.GetClockServiceAction().(*ClockService_ClockInfo_); ok {
		return x.ClockInfo
	}
	return nil
}

func (m *ClockService) GetClockRequest() *ClockService_ClockRequest {
	if x, ok := m.GetClockServiceAction().(*ClockService_ClockRequest_); ok {
		return x.ClockRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClockService) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClockService_ClockInfo_)(nil),
		(*ClockService_ClockRequest_)(nil),
	}
}

type ClockService_ClockInfo struct {
	Time                 uint32     `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	ClockType            ClockType  `protobuf:"varint,2,opt,name=clock_type,json=clockType,proto3,enum=api.clock.ClockType" json:"clock_type,omitempty"`
	StatusType           StatusType `protobuf:"varint,3,opt,name=status_type,json=statusType,proto3,enum=api.clock.StatusType" json:"status_type,omitempty"`
	Meta                 string     `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClockService_ClockInfo) Reset()         { *m = ClockService_ClockInfo{} }
func (m *ClockService_ClockInfo) String() string { return proto.CompactTextString(m) }
func (*ClockService_ClockInfo) ProtoMessage()    {}
func (*ClockService_ClockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{0, 0}
}

func (m *ClockService_ClockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockService_ClockInfo.Unmarshal(m, b)
}
func (m *ClockService_ClockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockService_ClockInfo.Marshal(b, m, deterministic)
}
func (m *ClockService_ClockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockService_ClockInfo.Merge(m, src)
}
func (m *ClockService_ClockInfo) XXX_Size() int {
	return xxx_messageInfo_ClockService_ClockInfo.Size(m)
}
func (m *ClockService_ClockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockService_ClockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClockService_ClockInfo proto.InternalMessageInfo

func (m *ClockService_ClockInfo) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ClockService_ClockInfo) GetClockType() ClockType {
	if m != nil {
		return m.ClockType
	}
	return ClockType_FORWARD
}

func (m *ClockService_ClockInfo) GetStatusType() StatusType {
	if m != nil {
		return m.StatusType
	}
	return StatusType_OK
}

func (m *ClockService_ClockInfo) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type ClockService_ClockRequest struct {
	Time                 uint32     `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	ClockType            ClockType  `protobuf:"varint,2,opt,name=clock_type,json=clockType,proto3,enum=api.clock.ClockType" json:"clock_type,omitempty"`
	NumCycle             uint32     `protobuf:"varint,3,opt,name=num_cycle,json=numCycle,proto3" json:"num_cycle,omitempty"`
	CycleDuration        uint32     `protobuf:"varint,4,opt,name=cycle_duration,json=cycleDuration,proto3" json:"cycle_duration,omitempty"`
	CycleTime            uint32     `protobuf:"varint,5,opt,name=cycle_time,json=cycleTime,proto3" json:"cycle_time,omitempty"`
	StatusType           StatusType `protobuf:"varint,6,opt,name=status_type,json=statusType,proto3,enum=api.clock.StatusType" json:"status_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClockService_ClockRequest) Reset()         { *m = ClockService_ClockRequest{} }
func (m *ClockService_ClockRequest) String() string { return proto.CompactTextString(m) }
func (*ClockService_ClockRequest) ProtoMessage()    {}
func (*ClockService_ClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e96fed1976809896, []int{0, 1}
}

func (m *ClockService_ClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockService_ClockRequest.Unmarshal(m, b)
}
func (m *ClockService_ClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockService_ClockRequest.Marshal(b, m, deterministic)
}
func (m *ClockService_ClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockService_ClockRequest.Merge(m, src)
}
func (m *ClockService_ClockRequest) XXX_Size() int {
	return xxx_messageInfo_ClockService_ClockRequest.Size(m)
}
func (m *ClockService_ClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockService_ClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClockService_ClockRequest proto.InternalMessageInfo

func (m *ClockService_ClockRequest) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ClockService_ClockRequest) GetClockType() ClockType {
	if m != nil {
		return m.ClockType
	}
	return ClockType_FORWARD
}

func (m *ClockService_ClockRequest) GetNumCycle() uint32 {
	if m != nil {
		return m.NumCycle
	}
	return 0
}

func (m *ClockService_ClockRequest) GetCycleDuration() uint32 {
	if m != nil {
		return m.CycleDuration
	}
	return 0
}

func (m *ClockService_ClockRequest) GetCycleTime() uint32 {
	if m != nil {
		return m.CycleTime
	}
	return 0
}

func (m *ClockService_ClockRequest) GetStatusType() StatusType {
	if m != nil {
		return m.StatusType
	}
	return StatusType_OK
}

func init() {
	proto.RegisterEnum("api.clock.StatusType", StatusType_name, StatusType_value)
	proto.RegisterEnum("api.clock.ClockType", ClockType_name, ClockType_value)
	proto.RegisterType((*ClockService)(nil), "api.clock.ClockService")
	proto.RegisterType((*ClockService_ClockInfo)(nil), "api.clock.ClockService.ClockInfo")
	proto.RegisterType((*ClockService_ClockRequest)(nil), "api.clock.ClockService.ClockRequest")
}

func init() { proto.RegisterFile("simulation/clock/clock.proto", fileDescriptor_e96fed1976809896) }

var fileDescriptor_e96fed1976809896 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x37, 0xbb, 0xe9, 0xb6, 0x39, 0xdb, 0x94, 0x61, 0xa8, 0xb0, 0x54, 0x85, 0x2a, 0x2a,
	0xa5, 0x17, 0x09, 0xb4, 0xa8, 0xb7, 0x26, 0xdb, 0x6a, 0x65, 0x61, 0x23, 0x93, 0x80, 0xe0, 0x4d,
	0x48, 0xc7, 0xa9, 0x3b, 0x98, 0x2f, 0x93, 0x89, 0x98, 0xb7, 0xf1, 0x85, 0x7c, 0x19, 0x9f, 0x40,
	0xe6, 0x24, 0xbb, 0x86, 0xbd, 0x10, 0x2f, 0x7a, 0x93, 0x9c, 0x8f, 0xff, 0x39, 0xe7, 0xc7, 0x39,
	0x0c, 0x3c, 0xaa, 0x65, 0xd6, 0xa4, 0x89, 0x92, 0x45, 0xee, 0xf2, 0xb4, 0xe0, 0x5f, 0xbb, 0xaf,
	0x53, 0x56, 0x85, 0x2a, 0xa8, 0x95, 0x94, 0xd2, 0xc1, 0xc0, 0xd3, 0x5f, 0x26, 0x1c, 0x2e, 0xb4,
	0x15, 0x8a, 0xea, 0xbb, 0xe4, 0x82, 0xfa, 0x00, 0x98, 0x89, 0x65, 0x7e, 0x57, 0xcc, 0x8d, 0x53,
	0xe3, 0x6c, 0x76, 0xf1, 0xc4, 0xd9, 0x16, 0x38, 0x43, 0x71, 0xe7, 0xbc, 0xcf, 0xef, 0x8a, 0x9b,
	0x11, 0xb3, 0xf8, 0xc6, 0xa1, 0x4b, 0xb0, 0xbb, 0x1e, 0x95, 0xf8, 0xd6, 0x88, 0x5a, 0xcd, 0xc7,
	0xd8, 0xe6, 0xd9, 0x3f, 0xdb, 0xb0, 0x4e, 0x7b, 0x33, 0x62, 0x87, 0x7c, 0xe0, 0x9f, 0xfc, 0x34,
	0xc0, 0xda, 0xce, 0xa1, 0x14, 0x4c, 0x25, 0x33, 0x81, 0x60, 0x36, 0x43, 0x9b, 0x5e, 0x6e, 0x90,
	0x55, 0x5b, 0x0a, 0x9c, 0x75, 0x74, 0x71, 0xbc, 0x3b, 0x2b, 0x6a, 0x4b, 0xd1, 0x33, 0x6a, 0x93,
	0xbe, 0x82, 0x59, 0xad, 0x12, 0xd5, 0xd4, 0x5d, 0xd5, 0x04, 0xab, 0x1e, 0x0c, 0xaa, 0x42, 0xcc,
	0x62, 0x19, 0xd4, 0x5b, 0x5b, 0x03, 0x64, 0x42, 0x25, 0x73, 0xf3, 0xd4, 0x38, 0xb3, 0x18, 0xda,
	0x27, 0xbf, 0x8d, 0x7e, 0x89, 0x3d, 0xf3, 0xfd, 0x51, 0x3e, 0x04, 0x2b, 0x6f, 0xb2, 0x98, 0xb7,
	0x3c, 0xed, 0x18, 0x6d, 0x76, 0x90, 0x37, 0xd9, 0x42, 0xfb, 0xf4, 0x39, 0x1c, 0x61, 0x22, 0xfe,
	0xdc, 0x54, 0x78, 0x6a, 0x84, 0xb2, 0x99, 0x8d, 0xd1, 0xab, 0x3e, 0x48, 0x1f, 0x03, 0x74, 0x32,
	0x44, 0xda, 0x43, 0x89, 0x85, 0x91, 0x48, 0x73, 0xed, 0x2c, 0x62, 0xfa, 0x9f, 0x8b, 0xf0, 0x8f,
	0x81, 0x0e, 0x8f, 0xe8, 0x71, 0x3d, 0xec, 0xfc, 0x05, 0xc0, 0x5f, 0x3d, 0x9d, 0xc2, 0x38, 0x58,
	0x92, 0x91, 0xfe, 0xaf, 0xde, 0x11, 0x83, 0x1e, 0x80, 0xb9, 0x0a, 0x56, 0xd7, 0x64, 0x7c, 0xfe,
	0xa6, 0x3f, 0x2a, 0xca, 0x66, 0xb0, 0xff, 0x36, 0x60, 0x1f, 0x3d, 0x76, 0x45, 0x46, 0x5a, 0xe3,
	0x7b, 0x8b, 0x25, 0x31, 0xe8, 0x3e, 0x4c, 0xc2, 0xeb, 0x88, 0x8c, 0xa9, 0x05, 0x7b, 0x61, 0xe4,
	0xb1, 0x88, 0x4c, 0x74, 0x36, 0x8c, 0x82, 0x0f, 0xc4, 0xf4, 0x5f, 0x7f, 0x7a, 0xf9, 0x45, 0xaa,
	0x75, 0x73, 0xeb, 0xf0, 0x22, 0x73, 0xeb, 0x36, 0x17, 0x95, 0xf8, 0xb1, 0xf9, 0xc7, 0x49, 0x5a,
	0xae, 0x13, 0x37, 0x29, 0xa5, 0xbb, 0xfb, 0x12, 0x6e, 0xa7, 0xf8, 0x08, 0x2e, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xca, 0x93, 0x46, 0xd3, 0x24, 0x03, 0x00, 0x00,
}
