// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentType int32

const (
	AgentType_WALK    AgentType = 0
	AgentType_CAR     AgentType = 1
	AgentType_TRAIN   AgentType = 2
	AgentType_BICYCLE AgentType = 3
)

var AgentType_name = map[int32]string{
	0: "WALK",
	1: "CAR",
	2: "TRAIN",
	3: "BICYCLE",
}

var AgentType_value = map[string]int32{
	"WALK":    0,
	"CAR":     1,
	"TRAIN":   2,
	"BICYCLE": 3,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{0}
}

type AgentService struct {
	AgentId              uint32    `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Direction            uint32    `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                uint32    `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	AgentType            AgentType `protobuf:"varint,4,opt,name=agent_type,json=agentType,proto3,enum=api.agent.AgentType" json:"agent_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AgentService) Reset()         { *m = AgentService{} }
func (m *AgentService) String() string { return proto.CompactTextString(m) }
func (*AgentService) ProtoMessage()    {}
func (*AgentService) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{0}
}

func (m *AgentService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentService.Unmarshal(m, b)
}
func (m *AgentService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentService.Marshal(b, m, deterministic)
}
func (m *AgentService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentService.Merge(m, src)
}
func (m *AgentService) XXX_Size() int {
	return xxx_messageInfo_AgentService.Size(m)
}
func (m *AgentService) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentService.DiscardUnknown(m)
}

var xxx_messageInfo_AgentService proto.InternalMessageInfo

func (m *AgentService) GetAgentId() uint32 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *AgentService) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *AgentService) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *AgentService) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_WALK
}

type AgentService_Coord struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Height               float32  `protobuf:"fixed32,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentService_Coord) Reset()         { *m = AgentService_Coord{} }
func (m *AgentService_Coord) String() string { return proto.CompactTextString(m) }
func (*AgentService_Coord) ProtoMessage()    {}
func (*AgentService_Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_253ddf9934d56132, []int{0, 0}
}

func (m *AgentService_Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentService_Coord.Unmarshal(m, b)
}
func (m *AgentService_Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentService_Coord.Marshal(b, m, deterministic)
}
func (m *AgentService_Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentService_Coord.Merge(m, src)
}
func (m *AgentService_Coord) XXX_Size() int {
	return xxx_messageInfo_AgentService_Coord.Size(m)
}
func (m *AgentService_Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentService_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_AgentService_Coord proto.InternalMessageInfo

func (m *AgentService_Coord) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *AgentService_Coord) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *AgentService_Coord) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.agent.AgentType", AgentType_name, AgentType_value)
	proto.RegisterType((*AgentService)(nil), "api.agent.AgentService")
	proto.RegisterType((*AgentService_Coord)(nil), "api.agent.AgentService.Coord")
}

func init() { proto.RegisterFile("agent/agent.proto", fileDescriptor_253ddf9934d56132) }

var fileDescriptor_253ddf9934d56132 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x4d, 0xd2, 0x34, 0xcd, 0xf8, 0x41, 0x5c, 0x8a, 0x44, 0xf1, 0x50, 0x3c, 0x95, 0x22,
	0x09, 0x58, 0xf0, 0x9e, 0x06, 0x0f, 0xc1, 0xe2, 0x61, 0x2d, 0x88, 0x5e, 0xca, 0x36, 0x19, 0x92,
	0x85, 0x9a, 0x5d, 0xd2, 0x55, 0xcc, 0x93, 0xfa, 0x3a, 0x92, 0x49, 0x5b, 0x2f, 0xbb, 0xff, 0x0f,
	0x98, 0xdf, 0x30, 0x70, 0x29, 0x4a, 0xac, 0x4d, 0x4c, 0x6f, 0xa4, 0x1b, 0x65, 0x14, 0xf3, 0x85,
	0x96, 0x11, 0x05, 0x77, 0xbf, 0x16, 0x9c, 0x25, 0x9d, 0x7a, 0xc5, 0xe6, 0x5b, 0xe6, 0xc8, 0xae,
	0x61, 0x44, 0xcd, 0x5a, 0x16, 0xa1, 0x35, 0xb1, 0xa6, 0xe7, 0xdc, 0x23, 0x9f, 0x15, 0xec, 0x16,
	0xfc, 0x42, 0x36, 0x98, 0x1b, 0xa9, 0xea, 0xd0, 0xa6, 0xee, 0x3f, 0x60, 0x63, 0x70, 0x77, 0x1a,
	0xb1, 0x08, 0x1d, 0x6a, 0x7a, 0xc3, 0xe6, 0x00, 0xfd, 0x38, 0xd3, 0x6a, 0x0c, 0x07, 0x13, 0x6b,
	0x7a, 0xf1, 0x30, 0x8e, 0x8e, 0xfc, 0x88, 0xd8, 0xab, 0x56, 0x23, 0xf7, 0xc5, 0x41, 0xde, 0xa4,
	0xe0, 0xa6, 0x4a, 0x35, 0x05, 0x0b, 0xc0, 0xd9, 0x0a, 0x43, 0x7b, 0xd8, 0xbc, 0x93, 0x94, 0xec,
	0xe9, 0x5d, 0xa2, 0x6a, 0x76, 0x05, 0xc3, 0x0a, 0x65, 0x59, 0x19, 0x02, 0xdb, 0x7c, 0xef, 0x66,
	0x8f, 0xe0, 0x1f, 0x87, 0xb3, 0x11, 0x0c, 0xde, 0x92, 0xe5, 0x73, 0x70, 0xc2, 0x3c, 0x70, 0xd2,
	0x84, 0x07, 0x16, 0xf3, 0xc1, 0x5d, 0xf1, 0x24, 0x7b, 0x09, 0x6c, 0x76, 0x0a, 0xde, 0x22, 0x4b,
	0xdf, 0xd3, 0xe5, 0x53, 0xe0, 0x2c, 0xee, 0x3f, 0x66, 0xa5, 0x34, 0xd5, 0xd7, 0x26, 0xca, 0xd5,
	0x67, 0xbc, 0x6b, 0x6b, 0x6c, 0xf0, 0xe7, 0xf0, 0xaf, 0xc5, 0x56, 0x57, 0x22, 0x16, 0x5a, 0xf6,
	0x07, 0xdd, 0x0c, 0xe9, 0xa2, 0xf3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0x87, 0xc4, 0x4c,
	0x66, 0x01, 0x00, 0x00,
}
