// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/participant/participant.proto

package participant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/synerex/synerex_alpha/api/simulation/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProviderType int32

const (
	ProviderType_SCENARIO      ProviderType = 0
	ProviderType_AREA          ProviderType = 1
	ProviderType_CAR           ProviderType = 2
	ProviderType_PED           ProviderType = 3
	ProviderType_ROUTE         ProviderType = 4
	ProviderType_VISUALIZATION ProviderType = 5
)

var ProviderType_name = map[int32]string{
	0: "SCENARIO",
	1: "AREA",
	2: "CAR",
	3: "PED",
	4: "ROUTE",
	5: "VISUALIZATION",
}

var ProviderType_value = map[string]int32{
	"SCENARIO":      0,
	"AREA":          1,
	"CAR":           2,
	"PED":           3,
	"ROUTE":         4,
	"VISUALIZATION": 5,
}

func (x ProviderType) String() string {
	return proto.EnumName(ProviderType_name, int32(x))
}

func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6631733b0a9fa50e, []int{0}
}

type RegistParticipantRequest struct {
	Participant          *Participant `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegistParticipantRequest) Reset()         { *m = RegistParticipantRequest{} }
func (m *RegistParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*RegistParticipantRequest) ProtoMessage()    {}
func (*RegistParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6631733b0a9fa50e, []int{0}
}

func (m *RegistParticipantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistParticipantRequest.Unmarshal(m, b)
}
func (m *RegistParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistParticipantRequest.Marshal(b, m, deterministic)
}
func (m *RegistParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistParticipantRequest.Merge(m, src)
}
func (m *RegistParticipantRequest) XXX_Size() int {
	return xxx_messageInfo_RegistParticipantRequest.Size(m)
}
func (m *RegistParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistParticipantRequest proto.InternalMessageInfo

func (m *RegistParticipantRequest) GetParticipant() *Participant {
	if m != nil {
		return m.Participant
	}
	return nil
}

type RegistParticipantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistParticipantResponse) Reset()         { *m = RegistParticipantResponse{} }
func (m *RegistParticipantResponse) String() string { return proto.CompactTextString(m) }
func (*RegistParticipantResponse) ProtoMessage()    {}
func (*RegistParticipantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6631733b0a9fa50e, []int{1}
}

func (m *RegistParticipantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistParticipantResponse.Unmarshal(m, b)
}
func (m *RegistParticipantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistParticipantResponse.Marshal(b, m, deterministic)
}
func (m *RegistParticipantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistParticipantResponse.Merge(m, src)
}
func (m *RegistParticipantResponse) XXX_Size() int {
	return xxx_messageInfo_RegistParticipantResponse.Size(m)
}
func (m *RegistParticipantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistParticipantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistParticipantResponse proto.InternalMessageInfo

type SetParticipantsRequest struct {
	Participants         []*Participant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetParticipantsRequest) Reset()         { *m = SetParticipantsRequest{} }
func (m *SetParticipantsRequest) String() string { return proto.CompactTextString(m) }
func (*SetParticipantsRequest) ProtoMessage()    {}
func (*SetParticipantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6631733b0a9fa50e, []int{2}
}

func (m *SetParticipantsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParticipantsRequest.Unmarshal(m, b)
}
func (m *SetParticipantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParticipantsRequest.Marshal(b, m, deterministic)
}
func (m *SetParticipantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParticipantsRequest.Merge(m, src)
}
func (m *SetParticipantsRequest) XXX_Size() int {
	return xxx_messageInfo_SetParticipantsRequest.Size(m)
}
func (m *SetParticipantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParticipantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetParticipantsRequest proto.InternalMessageInfo

func (m *SetParticipantsRequest) GetParticipants() []*Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

type SetParticipantsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetParticipantsResponse) Reset()         { *m = SetParticipantsResponse{} }
func (m *SetParticipantsResponse) String() string { return proto.CompactTextString(m) }
func (*SetParticipantsResponse) ProtoMessage()    {}
func (*SetParticipantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6631733b0a9fa50e, []int{3}
}

func (m *SetParticipantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParticipantsResponse.Unmarshal(m, b)
}
func (m *SetParticipantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParticipantsResponse.Marshal(b, m, deterministic)
}
func (m *SetParticipantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParticipantsResponse.Merge(m, src)
}
func (m *SetParticipantsResponse) XXX_Size() int {
	return xxx_messageInfo_SetParticipantsResponse.Size(m)
}
func (m *SetParticipantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParticipantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetParticipantsResponse proto.InternalMessageInfo

type Participant struct {
	ChannelId            *ChannelId       `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ProviderType         ProviderType     `protobuf:"varint,2,opt,name=provider_type,json=providerType,proto3,enum=api.participant.ProviderType" json:"provider_type,omitempty"`
	AreaId               uint64           `protobuf:"varint,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	AgentType            common.AgentType `protobuf:"varint,4,opt,name=agent_type,json=agentType,proto3,enum=api.common.AgentType" json:"agent_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Participant) Reset()         { *m = Participant{} }
func (m *Participant) String() string { return proto.CompactTextString(m) }
func (*Participant) ProtoMessage()    {}
func (*Participant) Descriptor() ([]byte, []int) {
	return fileDescriptor_6631733b0a9fa50e, []int{4}
}

func (m *Participant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participant.Unmarshal(m, b)
}
func (m *Participant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participant.Marshal(b, m, deterministic)
}
func (m *Participant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participant.Merge(m, src)
}
func (m *Participant) XXX_Size() int {
	return xxx_messageInfo_Participant.Size(m)
}
func (m *Participant) XXX_DiscardUnknown() {
	xxx_messageInfo_Participant.DiscardUnknown(m)
}

var xxx_messageInfo_Participant proto.InternalMessageInfo

func (m *Participant) GetChannelId() *ChannelId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *Participant) GetProviderType() ProviderType {
	if m != nil {
		return m.ProviderType
	}
	return ProviderType_SCENARIO
}

func (m *Participant) GetAreaId() uint64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *Participant) GetAgentType() common.AgentType {
	if m != nil {
		return m.AgentType
	}
	return common.AgentType_PEDESTRIAN
}

type ChannelId struct {
	ParticipantChannelId uint64   `protobuf:"varint,1,opt,name=participant_channel_id,json=participantChannelId,proto3" json:"participant_channel_id,omitempty"`
	AreaChannelId        uint64   `protobuf:"varint,2,opt,name=area_channel_id,json=areaChannelId,proto3" json:"area_channel_id,omitempty"`
	AgentChannelId       uint64   `protobuf:"varint,3,opt,name=agent_channel_id,json=agentChannelId,proto3" json:"agent_channel_id,omitempty"`
	ClockChannelId       uint64   `protobuf:"varint,4,opt,name=clock_channel_id,json=clockChannelId,proto3" json:"clock_channel_id,omitempty"`
	RouteChannelId       uint64   `protobuf:"varint,5,opt,name=route_channel_id,json=routeChannelId,proto3" json:"route_channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelId) Reset()         { *m = ChannelId{} }
func (m *ChannelId) String() string { return proto.CompactTextString(m) }
func (*ChannelId) ProtoMessage()    {}
func (*ChannelId) Descriptor() ([]byte, []int) {
	return fileDescriptor_6631733b0a9fa50e, []int{5}
}

func (m *ChannelId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelId.Unmarshal(m, b)
}
func (m *ChannelId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelId.Marshal(b, m, deterministic)
}
func (m *ChannelId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelId.Merge(m, src)
}
func (m *ChannelId) XXX_Size() int {
	return xxx_messageInfo_ChannelId.Size(m)
}
func (m *ChannelId) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelId.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelId proto.InternalMessageInfo

func (m *ChannelId) GetParticipantChannelId() uint64 {
	if m != nil {
		return m.ParticipantChannelId
	}
	return 0
}

func (m *ChannelId) GetAreaChannelId() uint64 {
	if m != nil {
		return m.AreaChannelId
	}
	return 0
}

func (m *ChannelId) GetAgentChannelId() uint64 {
	if m != nil {
		return m.AgentChannelId
	}
	return 0
}

func (m *ChannelId) GetClockChannelId() uint64 {
	if m != nil {
		return m.ClockChannelId
	}
	return 0
}

func (m *ChannelId) GetRouteChannelId() uint64 {
	if m != nil {
		return m.RouteChannelId
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.participant.ProviderType", ProviderType_name, ProviderType_value)
	proto.RegisterType((*RegistParticipantRequest)(nil), "api.participant.RegistParticipantRequest")
	proto.RegisterType((*RegistParticipantResponse)(nil), "api.participant.RegistParticipantResponse")
	proto.RegisterType((*SetParticipantsRequest)(nil), "api.participant.SetParticipantsRequest")
	proto.RegisterType((*SetParticipantsResponse)(nil), "api.participant.SetParticipantsResponse")
	proto.RegisterType((*Participant)(nil), "api.participant.Participant")
	proto.RegisterType((*ChannelId)(nil), "api.participant.ChannelId")
}

func init() {
	proto.RegisterFile("simulation/participant/participant.proto", fileDescriptor_6631733b0a9fa50e)
}

var fileDescriptor_6631733b0a9fa50e = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x6b, 0x30, 0x49, 0x18, 0x20, 0x71, 0x57, 0x6d, 0x42, 0xd2, 0x3f, 0x42, 0x3e, 0x54,
	0x56, 0x0f, 0x20, 0xa5, 0xb9, 0x54, 0x55, 0xab, 0x3a, 0x94, 0x83, 0xa5, 0x2a, 0x44, 0x0b, 0xc9,
	0x81, 0x0b, 0xda, 0x98, 0x15, 0xac, 0x0a, 0xde, 0xad, 0x77, 0xa9, 0xca, 0xb3, 0xf6, 0x01, 0xfa,
	0x1a, 0x95, 0xd7, 0x18, 0x86, 0x10, 0xa9, 0x27, 0xcf, 0xce, 0xfc, 0xbe, 0x6f, 0x66, 0xd6, 0x5a,
	0x08, 0xb4, 0x58, 0x2c, 0xe7, 0xcc, 0x08, 0x99, 0x74, 0x14, 0x4b, 0x8d, 0x88, 0x85, 0x62, 0x89,
	0xc1, 0x71, 0x5b, 0xa5, 0xd2, 0x48, 0x72, 0xc2, 0x94, 0x68, 0xa3, 0xf4, 0xc5, 0x5b, 0x24, 0x8d,
	0xe5, 0x62, 0xb1, 0xf9, 0xe4, 0x02, 0x7f, 0x04, 0x4d, 0xca, 0xa7, 0x42, 0x9b, 0xdb, 0xad, 0x88,
	0xf2, 0x9f, 0x4b, 0xae, 0x0d, 0xf9, 0x02, 0x35, 0x64, 0xd5, 0x74, 0x5a, 0x4e, 0x50, 0xbb, 0x7c,
	0xdd, 0x7e, 0xd4, 0xa2, 0x8d, 0x95, 0x58, 0xe0, 0xbf, 0x82, 0xf3, 0x27, 0xbc, 0xb5, 0x92, 0x89,
	0xe6, 0xfe, 0x08, 0x4e, 0x07, 0x1c, 0x57, 0x74, 0xd1, 0xf6, 0x2b, 0xd4, 0x91, 0x8b, 0x6e, 0x3a,
	0xad, 0xf2, 0x7f, 0xfb, 0xee, 0x28, 0xfc, 0x73, 0x38, 0xdb, 0xf3, 0x5e, 0xb7, 0xfd, 0xe3, 0x40,
	0x0d, 0x15, 0xc8, 0x47, 0x80, 0x78, 0xc6, 0x92, 0x84, 0xcf, 0xc7, 0x62, 0xb2, 0x5e, 0xf1, 0x62,
	0xaf, 0x55, 0x37, 0x47, 0xa2, 0x09, 0xad, 0xc6, 0x45, 0x48, 0xae, 0xa1, 0xa1, 0x52, 0xf9, 0x4b,
	0x4c, 0x78, 0x3a, 0x36, 0x2b, 0xc5, 0x9b, 0xa5, 0x96, 0x13, 0x1c, 0x5f, 0xbe, 0xd9, 0x1f, 0x74,
	0x4d, 0x0d, 0x57, 0x8a, 0xd3, 0xba, 0x42, 0x27, 0x72, 0x06, 0x87, 0x2c, 0xe5, 0x2c, 0xeb, 0x5d,
	0x6e, 0x39, 0x81, 0x4b, 0x0f, 0xb2, 0x63, 0x34, 0x21, 0x57, 0x00, 0x6c, 0xca, 0x13, 0x93, 0x3b,
	0xbb, 0xd6, 0xf9, 0xa5, 0x75, 0x5e, 0xff, 0xbe, 0x30, 0xab, 0x5a, 0xc7, 0x2a, 0x2b, 0x42, 0xff,
	0xaf, 0x03, 0xd5, 0xcd, 0xac, 0xe4, 0x0a, 0x4e, 0xd1, 0x18, 0xe3, 0x47, 0x7b, 0xba, 0xf4, 0x05,
	0xaa, 0x6e, 0x55, 0xef, 0xe0, 0xc4, 0x8e, 0x84, 0xf0, 0x92, 0xc5, 0x1b, 0x59, 0x7a, 0xcb, 0x05,
	0xe0, 0xe5, 0x13, 0x22, 0x30, 0xdf, 0xe1, 0xd8, 0xe6, 0x77, 0xc8, 0x78, 0x2e, 0xe3, 0x1f, 0x98,
	0x74, 0x73, 0xd2, 0xe6, 0x77, 0xc8, 0x54, 0x2e, 0x0d, 0xc7, 0x64, 0x25, 0x27, 0x6d, 0x7e, 0x43,
	0xbe, 0xbf, 0x87, 0x3a, 0xbe, 0x56, 0x52, 0x87, 0xa3, 0x41, 0xb7, 0x77, 0x13, 0xd2, 0xa8, 0xef,
	0x3d, 0x23, 0x47, 0xe0, 0x86, 0xb4, 0x17, 0x7a, 0x0e, 0x39, 0x84, 0x72, 0x37, 0xa4, 0x5e, 0x29,
	0x0b, 0x6e, 0x7b, 0xdf, 0xbc, 0x32, 0xa9, 0x42, 0x85, 0xf6, 0xef, 0x86, 0x3d, 0xcf, 0x25, 0xcf,
	0xa1, 0x71, 0x1f, 0x0d, 0xee, 0xc2, 0xef, 0xd1, 0x28, 0x1c, 0x46, 0xfd, 0x1b, 0xaf, 0x72, 0xfd,
	0x79, 0xf4, 0x69, 0x2a, 0xcc, 0x6c, 0xf9, 0x90, 0xdd, 0x73, 0x47, 0xaf, 0x12, 0x9e, 0xf2, 0xdf,
	0xc5, 0x77, 0xcc, 0xe6, 0x6a, 0xc6, 0x3a, 0x4c, 0x89, 0xce, 0xd3, 0x2f, 0xf2, 0xe1, 0xc0, 0xbe,
	0xaa, 0x0f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36, 0xba, 0x4f, 0x51, 0xb2, 0x03, 0x00, 0x00,
}
