// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adservice/adservice.proto

package adservice // import "github.com/synerex/synerex_alpha/api/adservice"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdService struct {
	Target               *AdTarget          `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	ContentType          string             `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	AmountTime           *duration.Duration `protobuf:"bytes,3,opt,name=amount_time,json=amountTime,proto3" json:"amount_time,omitempty"`
	Price                uint32             `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AdService) Reset()         { *m = AdService{} }
func (m *AdService) String() string { return proto.CompactTextString(m) }
func (*AdService) ProtoMessage()    {}
func (*AdService) Descriptor() ([]byte, []int) {
	return fileDescriptor_adservice_a62272eaa827c207, []int{0}
}
func (m *AdService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdService.Unmarshal(m, b)
}
func (m *AdService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdService.Marshal(b, m, deterministic)
}
func (dst *AdService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdService.Merge(dst, src)
}
func (m *AdService) XXX_Size() int {
	return xxx_messageInfo_AdService.Size(m)
}
func (m *AdService) XXX_DiscardUnknown() {
	xxx_messageInfo_AdService.DiscardUnknown(m)
}

var xxx_messageInfo_AdService proto.InternalMessageInfo

func (m *AdService) GetTarget() *AdTarget {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AdService) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *AdService) GetAmountTime() *duration.Duration {
	if m != nil {
		return m.AmountTime
	}
	return nil
}

func (m *AdService) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AdTarget struct {
	Age                  []bool   `protobuf:"varint,1,rep,packed,name=age,proto3" json:"age,omitempty"`
	Sex                  []bool   `protobuf:"varint,2,rep,packed,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdTarget) Reset()         { *m = AdTarget{} }
func (m *AdTarget) String() string { return proto.CompactTextString(m) }
func (*AdTarget) ProtoMessage()    {}
func (*AdTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_adservice_a62272eaa827c207, []int{1}
}
func (m *AdTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdTarget.Unmarshal(m, b)
}
func (m *AdTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdTarget.Marshal(b, m, deterministic)
}
func (dst *AdTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdTarget.Merge(dst, src)
}
func (m *AdTarget) XXX_Size() int {
	return xxx_messageInfo_AdTarget.Size(m)
}
func (m *AdTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_AdTarget.DiscardUnknown(m)
}

var xxx_messageInfo_AdTarget proto.InternalMessageInfo

func (m *AdTarget) GetAge() []bool {
	if m != nil {
		return m.Age
	}
	return nil
}

func (m *AdTarget) GetSex() []bool {
	if m != nil {
		return m.Sex
	}
	return nil
}

func init() {
	proto.RegisterType((*AdService)(nil), "api.adservice.AdService")
	proto.RegisterType((*AdTarget)(nil), "api.adservice.AdTarget")
}

func init() {
	proto.RegisterFile("adservice/adservice.proto", fileDescriptor_adservice_a62272eaa827c207)
}

var fileDescriptor_adservice_a62272eaa827c207 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xc9, 0xaa, 0x63, 0x4b, 0x1d, 0x48, 0x10, 0xcc, 0x3c, 0x48, 0xdd, 0xa9, 0xa7, 0x17,
	0xd1, 0x9b, 0xb7, 0x89, 0x9f, 0xa0, 0xf6, 0xe4, 0x65, 0xa4, 0xed, 0xb3, 0x0b, 0xac, 0x4d, 0x48,
	0x53, 0x69, 0x3f, 0x96, 0xdf, 0x50, 0xda, 0xb4, 0x93, 0x9d, 0xf2, 0xf2, 0x7f, 0x3f, 0xfe, 0xfc,
	0x78, 0x74, 0x2b, 0x8b, 0x06, 0xed, 0x8f, 0xca, 0x51, 0x9c, 0x27, 0x30, 0x56, 0x3b, 0xcd, 0x36,
	0xd2, 0x28, 0x38, 0x87, 0x0f, 0x8f, 0xa5, 0xd6, 0xe5, 0x09, 0xc5, 0xb8, 0xcc, 0xda, 0x6f, 0x51,
	0xb4, 0x56, 0x3a, 0xa5, 0x6b, 0x8f, 0xef, 0x7e, 0x09, 0x5d, 0xef, 0x8b, 0x4f, 0x4f, 0x33, 0x41,
	0x97, 0x4e, 0xda, 0x12, 0x1d, 0x27, 0x11, 0x89, 0xc3, 0x97, 0x7b, 0xb8, 0x68, 0x83, 0x7d, 0x91,
	0x8e, 0xeb, 0x64, 0xc2, 0xd8, 0x13, 0xbd, 0xc9, 0x75, 0xed, 0xb0, 0x76, 0x07, 0xd7, 0x1b, 0xe4,
	0x8b, 0x88, 0xc4, 0xeb, 0x24, 0x9c, 0xb2, 0xb4, 0x37, 0xc8, 0xde, 0x68, 0x28, 0x2b, 0xdd, 0x0e,
	0x84, 0xaa, 0x90, 0x07, 0x63, 0xf1, 0x16, 0xbc, 0x17, 0xcc, 0x5e, 0xf0, 0x31, 0x79, 0x25, 0xd4,
	0xd3, 0xa9, 0xaa, 0x90, 0xdd, 0xd1, 0x6b, 0x63, 0x55, 0x8e, 0xfc, 0x2a, 0x22, 0xf1, 0x26, 0xf1,
	0x9f, 0x1d, 0xd0, 0xd5, 0x2c, 0xc2, 0x6e, 0x69, 0x20, 0x4b, 0xe4, 0x24, 0x0a, 0xe2, 0x55, 0x32,
	0x8c, 0x43, 0xd2, 0x60, 0xc7, 0x17, 0x3e, 0x69, 0xb0, 0x7b, 0x7f, 0xfe, 0x82, 0x52, 0xb9, 0x63,
	0x9b, 0x41, 0xae, 0x2b, 0xd1, 0xf4, 0x35, 0x5a, 0xec, 0xe6, 0xf7, 0x20, 0x4f, 0xe6, 0x28, 0x85,
	0x34, 0xea, 0xff, 0x94, 0xd9, 0x72, 0xd4, 0x7a, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x08,
	0x6a, 0x96, 0x68, 0x01, 0x00, 0x00,
}
