# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketing/marketing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from api.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='marketing/marketing.proto',
  package='api.marketing',
  syntax='proto3',
  serialized_options=_b('Z.github.com/synerex/synerex_alpha/api/marketing'),
  serialized_pb=_b('\n\x19marketing/marketing.proto\x12\rapi.marketing\x1a\x1egoogle/protobuf/duration.proto\x1a\x13\x63ommon/common.proto\"\xa6\x02\n\x10MarketingService\x12\x13\n\x0boperator_id\x18\x01 \x01(\x05\x12\'\n\x0c\x64\x65part_point\x18\x04 \x01(\x0b\x32\x11.api.common.Place\x12\'\n\x0c\x61rrive_point\x18\x05 \x01(\x0b\x32\x11.api.common.Place\x12%\n\x0b\x64\x65part_time\x18\x06 \x01(\x0b\x32\x10.api.common.Time\x12%\n\x0b\x61rrive_time\x18\x07 \x01(\x0b\x32\x10.api.common.Time\x12.\n\x0b\x61mount_time\x18\x08 \x01(\x0b\x32\x19.google.protobuf.Duration\x12-\n\ndelay_time\x18\r \x01(\x0b\x32\x19.google.protobuf.DurationB0Z.github.com/synerex/synerex_alpha/api/marketingb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,common_dot_common__pb2.DESCRIPTOR,])




_MARKETINGSERVICE = _descriptor.Descriptor(
  name='MarketingService',
  full_name='api.marketing.MarketingService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator_id', full_name='api.marketing.MarketingService.operator_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depart_point', full_name='api.marketing.MarketingService.depart_point', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_point', full_name='api.marketing.MarketingService.arrive_point', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depart_time', full_name='api.marketing.MarketingService.depart_time', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_time', full_name='api.marketing.MarketingService.arrive_time', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_time', full_name='api.marketing.MarketingService.amount_time', index=5,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay_time', full_name='api.marketing.MarketingService.delay_time', index=6,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=392,
)

_MARKETINGSERVICE.fields_by_name['depart_point'].message_type = common_dot_common__pb2._PLACE
_MARKETINGSERVICE.fields_by_name['arrive_point'].message_type = common_dot_common__pb2._PLACE
_MARKETINGSERVICE.fields_by_name['depart_time'].message_type = common_dot_common__pb2._TIME
_MARKETINGSERVICE.fields_by_name['arrive_time'].message_type = common_dot_common__pb2._TIME
_MARKETINGSERVICE.fields_by_name['amount_time'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_MARKETINGSERVICE.fields_by_name['delay_time'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['MarketingService'] = _MARKETINGSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarketingService = _reflection.GeneratedProtocolMessageType('MarketingService', (_message.Message,), {
  'DESCRIPTOR' : _MARKETINGSERVICE,
  '__module__' : 'marketing.marketing_pb2'
  # @@protoc_insertion_point(class_scope:api.marketing.MarketingService)
  })
_sym_db.RegisterMessage(MarketingService)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
