// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/agent/agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusType int32

const (
	StatusType_OK   StatusType = 0
	StatusType_NG   StatusType = 1
	StatusType_NONE StatusType = 2
)

var StatusType_name = map[int32]string{
	0: "OK",
	1: "NG",
	2: "NONE",
}

var StatusType_value = map[string]int32{
	"OK":   0,
	"NG":   1,
	"NONE": 2,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{0}
}

type AgentType int32

const (
	AgentType_PEDESTRIAN AgentType = 0
	AgentType_CAR        AgentType = 1
	AgentType_TRAIN      AgentType = 2
	AgentType_BICYCLE    AgentType = 3
)

var AgentType_name = map[int32]string{
	0: "PEDESTRIAN",
	1: "CAR",
	2: "TRAIN",
	3: "BICYCLE",
}

var AgentType_value = map[string]int32{
	"PEDESTRIAN": 0,
	"CAR":        1,
	"TRAIN":      2,
	"BICYCLE":    3,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{1}
}

type AgentService struct {
	// Types that are valid to be assigned to AreaServiceAction:
	//	*AgentService_AgentInfo_
	//	*AgentService_AgentsInfo_
	//	*AgentService_AgentRequest_
	AreaServiceAction    isAgentService_AreaServiceAction `protobuf_oneof:"AreaServiceAction"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *AgentService) Reset()         { *m = AgentService{} }
func (m *AgentService) String() string { return proto.CompactTextString(m) }
func (*AgentService) ProtoMessage()    {}
func (*AgentService) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{0}
}

func (m *AgentService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentService.Unmarshal(m, b)
}
func (m *AgentService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentService.Marshal(b, m, deterministic)
}
func (m *AgentService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentService.Merge(m, src)
}
func (m *AgentService) XXX_Size() int {
	return xxx_messageInfo_AgentService.Size(m)
}
func (m *AgentService) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentService.DiscardUnknown(m)
}

var xxx_messageInfo_AgentService proto.InternalMessageInfo

type isAgentService_AreaServiceAction interface {
	isAgentService_AreaServiceAction()
}

type AgentService_AgentInfo_ struct {
	AgentInfo *AgentService_AgentInfo `protobuf:"bytes,1,opt,name=agent_info,json=agentInfo,proto3,oneof"`
}

type AgentService_AgentsInfo_ struct {
	AgentsInfo *AgentService_AgentsInfo `protobuf:"bytes,2,opt,name=agents_info,json=agentsInfo,proto3,oneof"`
}

type AgentService_AgentRequest_ struct {
	AgentRequest *AgentService_AgentRequest `protobuf:"bytes,3,opt,name=agent_request,json=agentRequest,proto3,oneof"`
}

func (*AgentService_AgentInfo_) isAgentService_AreaServiceAction() {}

func (*AgentService_AgentsInfo_) isAgentService_AreaServiceAction() {}

func (*AgentService_AgentRequest_) isAgentService_AreaServiceAction() {}

func (m *AgentService) GetAreaServiceAction() isAgentService_AreaServiceAction {
	if m != nil {
		return m.AreaServiceAction
	}
	return nil
}

func (m *AgentService) GetAgentInfo() *AgentService_AgentInfo {
	if x, ok := m.GetAreaServiceAction().(*AgentService_AgentInfo_); ok {
		return x.AgentInfo
	}
	return nil
}

func (m *AgentService) GetAgentsInfo() *AgentService_AgentsInfo {
	if x, ok := m.GetAreaServiceAction().(*AgentService_AgentsInfo_); ok {
		return x.AgentsInfo
	}
	return nil
}

func (m *AgentService) GetAgentRequest() *AgentService_AgentRequest {
	if x, ok := m.GetAreaServiceAction().(*AgentService_AgentRequest_); ok {
		return x.AgentRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AgentService) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AgentService_AgentInfo_)(nil),
		(*AgentService_AgentsInfo_)(nil),
		(*AgentService_AgentRequest_)(nil),
	}
}

type AgentService_AgentInfo struct {
	Time                 uint32     `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	AgentId              uint32     `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName            string     `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentType            AgentType  `protobuf:"varint,4,opt,name=agent_type,json=agentType,proto3,enum=api.agent.AgentType" json:"agent_type,omitempty"`
	Route                *Route     `protobuf:"bytes,5,opt,name=route,proto3" json:"route,omitempty"`
	Rule                 *Rule      `protobuf:"bytes,6,opt,name=rule,proto3" json:"rule,omitempty"`
	StatusType           StatusType `protobuf:"varint,7,opt,name=status_type,json=statusType,proto3,enum=api.agent.StatusType" json:"status_type,omitempty"`
	Meta                 string     `protobuf:"bytes,8,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AgentService_AgentInfo) Reset()         { *m = AgentService_AgentInfo{} }
func (m *AgentService_AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentService_AgentInfo) ProtoMessage()    {}
func (*AgentService_AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{0, 0}
}

func (m *AgentService_AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentService_AgentInfo.Unmarshal(m, b)
}
func (m *AgentService_AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentService_AgentInfo.Marshal(b, m, deterministic)
}
func (m *AgentService_AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentService_AgentInfo.Merge(m, src)
}
func (m *AgentService_AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentService_AgentInfo.Size(m)
}
func (m *AgentService_AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentService_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentService_AgentInfo proto.InternalMessageInfo

func (m *AgentService_AgentInfo) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AgentService_AgentInfo) GetAgentId() uint32 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *AgentService_AgentInfo) GetAgentName() string {
	if m != nil {
		return m.AgentName
	}
	return ""
}

func (m *AgentService_AgentInfo) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_PEDESTRIAN
}

func (m *AgentService_AgentInfo) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *AgentService_AgentInfo) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *AgentService_AgentInfo) GetStatusType() StatusType {
	if m != nil {
		return m.StatusType
	}
	return StatusType_OK
}

func (m *AgentService_AgentInfo) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type AgentService_AgentsInfo struct {
	Time                 uint32                    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	AgentInfo            []*AgentService_AgentInfo `protobuf:"bytes,2,rep,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	StatusType           StatusType                `protobuf:"varint,3,opt,name=status_type,json=statusType,proto3,enum=api.agent.StatusType" json:"status_type,omitempty"`
	Meta                 string                    `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AgentService_AgentsInfo) Reset()         { *m = AgentService_AgentsInfo{} }
func (m *AgentService_AgentsInfo) String() string { return proto.CompactTextString(m) }
func (*AgentService_AgentsInfo) ProtoMessage()    {}
func (*AgentService_AgentsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{0, 1}
}

func (m *AgentService_AgentsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentService_AgentsInfo.Unmarshal(m, b)
}
func (m *AgentService_AgentsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentService_AgentsInfo.Marshal(b, m, deterministic)
}
func (m *AgentService_AgentsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentService_AgentsInfo.Merge(m, src)
}
func (m *AgentService_AgentsInfo) XXX_Size() int {
	return xxx_messageInfo_AgentService_AgentsInfo.Size(m)
}
func (m *AgentService_AgentsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentService_AgentsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentService_AgentsInfo proto.InternalMessageInfo

func (m *AgentService_AgentsInfo) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AgentService_AgentsInfo) GetAgentInfo() []*AgentService_AgentInfo {
	if m != nil {
		return m.AgentInfo
	}
	return nil
}

func (m *AgentService_AgentsInfo) GetStatusType() StatusType {
	if m != nil {
		return m.StatusType
	}
	return StatusType_OK
}

func (m *AgentService_AgentsInfo) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type AgentService_AgentRequest struct {
	Time                 uint32    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	AgentId              uint32    `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName            string    `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentType            AgentType `protobuf:"varint,4,opt,name=agent_type,json=agentType,proto3,enum=api.agent.AgentType" json:"agent_type,omitempty"`
	Route                *Route    `protobuf:"bytes,5,opt,name=route,proto3" json:"route,omitempty"`
	Rule                 *Rule     `protobuf:"bytes,6,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AgentService_AgentRequest) Reset()         { *m = AgentService_AgentRequest{} }
func (m *AgentService_AgentRequest) String() string { return proto.CompactTextString(m) }
func (*AgentService_AgentRequest) ProtoMessage()    {}
func (*AgentService_AgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{0, 2}
}

func (m *AgentService_AgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentService_AgentRequest.Unmarshal(m, b)
}
func (m *AgentService_AgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentService_AgentRequest.Marshal(b, m, deterministic)
}
func (m *AgentService_AgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentService_AgentRequest.Merge(m, src)
}
func (m *AgentService_AgentRequest) XXX_Size() int {
	return xxx_messageInfo_AgentService_AgentRequest.Size(m)
}
func (m *AgentService_AgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentService_AgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentService_AgentRequest proto.InternalMessageInfo

func (m *AgentService_AgentRequest) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AgentService_AgentRequest) GetAgentId() uint32 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *AgentService_AgentRequest) GetAgentName() string {
	if m != nil {
		return m.AgentName
	}
	return ""
}

func (m *AgentService_AgentRequest) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_PEDESTRIAN
}

func (m *AgentService_AgentRequest) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *AgentService_AgentRequest) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type Route struct {
	Coord                *Route_Coord `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	Direction            float32      `protobuf:"fixed32,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                float32      `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Destination          float32      `protobuf:"fixed32,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Departure            float32      `protobuf:"fixed32,5,opt,name=departure,proto3" json:"departure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{1}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetCoord() *Route_Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *Route) GetDirection() float32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Route) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Route) GetDestination() float32 {
	if m != nil {
		return m.Destination
	}
	return 0
}

func (m *Route) GetDeparture() float32 {
	if m != nil {
		return m.Departure
	}
	return 0
}

type Route_Coord struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route_Coord) Reset()         { *m = Route_Coord{} }
func (m *Route_Coord) String() string { return proto.CompactTextString(m) }
func (*Route_Coord) ProtoMessage()    {}
func (*Route_Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{1, 0}
}

func (m *Route_Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route_Coord.Unmarshal(m, b)
}
func (m *Route_Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route_Coord.Marshal(b, m, deterministic)
}
func (m *Route_Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route_Coord.Merge(m, src)
}
func (m *Route_Coord) XXX_Size() int {
	return xxx_messageInfo_Route_Coord.Size(m)
}
func (m *Route_Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Route_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Route_Coord proto.InternalMessageInfo

func (m *Route_Coord) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Route_Coord) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Rule struct {
	RuleInfo             string   `protobuf:"bytes,1,opt,name=RuleInfo,proto3" json:"RuleInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{2}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetRuleInfo() string {
	if m != nil {
		return m.RuleInfo
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.agent.StatusType", StatusType_name, StatusType_value)
	proto.RegisterEnum("api.agent.AgentType", AgentType_name, AgentType_value)
	proto.RegisterType((*AgentService)(nil), "api.agent.AgentService")
	proto.RegisterType((*AgentService_AgentInfo)(nil), "api.agent.AgentService.AgentInfo")
	proto.RegisterType((*AgentService_AgentsInfo)(nil), "api.agent.AgentService.AgentsInfo")
	proto.RegisterType((*AgentService_AgentRequest)(nil), "api.agent.AgentService.AgentRequest")
	proto.RegisterType((*Route)(nil), "api.agent.Route")
	proto.RegisterType((*Route_Coord)(nil), "api.agent.Route.Coord")
	proto.RegisterType((*Rule)(nil), "api.agent.Rule")
}

func init() { proto.RegisterFile("simulation/agent/agent.proto", fileDescriptor_fce67ac898dc274e) }

var fileDescriptor_fce67ac898dc274e = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0x8e, 0x6f, 0x4d, 0x7c, 0xd2, 0xf6, 0xf7, 0x3f, 0x14, 0x64, 0xa2, 0x22, 0x85, 0x80, 0xaa,
	0xaa, 0x20, 0x47, 0x6a, 0x05, 0x6c, 0x58, 0xe0, 0x84, 0x88, 0x46, 0x45, 0x2e, 0x9a, 0x76, 0x03,
	0x9b, 0x6a, 0x1a, 0x4f, 0x5b, 0x4b, 0xf1, 0x05, 0x7b, 0x8c, 0xc8, 0x13, 0xb1, 0x63, 0xcb, 0x9b,
	0xb0, 0xe4, 0x59, 0xd0, 0x9c, 0xb1, 0x13, 0x13, 0xa1, 0x0a, 0xb6, 0x6c, 0x3c, 0xe7, 0xe6, 0x6f,
	0xbe, 0xef, 0xcc, 0x99, 0x81, 0xdd, 0x22, 0x8a, 0xcb, 0x39, 0x13, 0x51, 0x9a, 0x0c, 0xd9, 0x35,
	0x4f, 0x84, 0xfa, 0x7a, 0x59, 0x9e, 0x8a, 0x94, 0xd8, 0x2c, 0x8b, 0x3c, 0x0c, 0x0c, 0xbe, 0xb5,
	0x61, 0xd3, 0x97, 0xd6, 0x19, 0xcf, 0x3f, 0x45, 0x33, 0x4e, 0x46, 0x00, 0x98, 0xb9, 0x88, 0x92,
	0xab, 0xd4, 0xd5, 0xfa, 0xda, 0x7e, 0xf7, 0xf0, 0xa1, 0xb7, 0xfc, 0xc1, 0x6b, 0x16, 0x2b, 0x67,
	0x9a, 0x5c, 0xa5, 0xc7, 0x2d, 0x6a, 0xb3, 0xda, 0x21, 0x13, 0xe8, 0xa2, 0x53, 0x28, 0x10, 0x1d,
	0x41, 0x06, 0xb7, 0x82, 0x14, 0x15, 0x8a, 0xda, 0x1c, 0x3d, 0x72, 0x02, 0x5b, 0x8a, 0x4a, 0xce,
	0x3f, 0x96, 0xbc, 0x10, 0xae, 0x81, 0x40, 0x8f, 0x6f, 0x05, 0xa2, 0xaa, 0xf6, 0xb8, 0x45, 0x37,
	0x59, 0xc3, 0xef, 0x7d, 0xd1, 0xc1, 0x5e, 0xd2, 0x25, 0x04, 0x4c, 0x11, 0xc5, 0x1c, 0xf5, 0x6d,
	0x51, 0xb4, 0xc9, 0x7d, 0xe8, 0x54, 0xca, 0x43, 0xa4, 0xbc, 0x45, 0xdb, 0x4a, 0x52, 0x48, 0x1e,
	0xd4, 0x4d, 0x49, 0x58, 0xcc, 0x91, 0x86, 0x5d, 0xe9, 0x0d, 0x58, 0xcc, 0xc9, 0x51, 0x9d, 0x16,
	0x8b, 0x8c, 0xbb, 0x66, 0x5f, 0xdb, 0xdf, 0x3e, 0xdc, 0x59, 0x67, 0x79, 0xbe, 0xc8, 0x78, 0xf5,
	0x93, 0x34, 0xc9, 0x1e, 0x58, 0x79, 0x5a, 0x0a, 0xee, 0x5a, 0xa8, 0xca, 0x69, 0xd4, 0x53, 0x19,
	0xa7, 0x2a, 0x4d, 0x1e, 0x81, 0x99, 0x97, 0x73, 0xee, 0x6e, 0x60, 0xd9, 0x7f, 0xcd, 0xb2, 0x72,
	0xce, 0x29, 0x26, 0xc9, 0x73, 0xe8, 0x16, 0x82, 0x89, 0xb2, 0x50, 0x14, 0xda, 0x48, 0xe1, 0x6e,
	0xa3, 0xf6, 0x0c, 0xb3, 0xc8, 0x01, 0x8a, 0xa5, 0x2d, 0xfb, 0x10, 0x73, 0xc1, 0xdc, 0x0e, 0x4a,
	0x42, 0xbb, 0xf7, 0x55, 0x03, 0x58, 0x9d, 0xc9, 0x6f, 0x5b, 0xf5, 0xea, 0x97, 0x21, 0xd1, 0xfb,
	0xc6, 0x1f, 0x0d, 0x49, 0x73, 0x44, 0xd6, 0x08, 0x1b, 0x7f, 0x4b, 0xd8, 0x6c, 0x10, 0xfe, 0xa1,
	0x55, 0x33, 0x5c, 0x9d, 0xf5, 0xbf, 0x76, 0xba, 0xa3, 0x3b, 0xf0, 0xbf, 0x9f, 0x73, 0x56, 0x35,
	0xd4, 0x9f, 0xc9, 0x6b, 0x3d, 0xf8, 0xae, 0x81, 0x85, 0x50, 0xe4, 0x29, 0x58, 0xb3, 0x34, 0xcd,
	0xc3, 0xea, 0xb6, 0xde, 0x5b, 0xdf, 0xcb, 0x1b, 0xcb, 0x2c, 0x55, 0x45, 0x64, 0x17, 0xec, 0x30,
	0xca, 0x39, 0x82, 0x60, 0x27, 0x74, 0xba, 0x0a, 0x90, 0x1d, 0xb0, 0x8a, 0x8c, 0xf3, 0x10, 0xdb,
	0xa0, 0x53, 0xe5, 0x90, 0x3e, 0x74, 0x43, 0x5e, 0x88, 0x28, 0xc1, 0x17, 0x05, 0x7b, 0xa0, 0xd3,
	0x66, 0x08, 0x51, 0x79, 0xc6, 0x72, 0x51, 0xe6, 0x4a, 0xb3, 0x44, 0xad, 0x03, 0xbd, 0x27, 0x60,
	0x21, 0x07, 0xe2, 0x80, 0x31, 0x67, 0x02, 0x89, 0xea, 0x54, 0x9a, 0x18, 0x59, 0x12, 0x91, 0xe6,
	0x60, 0x00, 0xa6, 0xd4, 0x4e, 0x7a, 0xd0, 0x91, 0xeb, 0xb4, 0x7e, 0x87, 0x6c, 0xba, 0xf4, 0x0f,
	0xf6, 0x00, 0x56, 0x03, 0x42, 0x36, 0x40, 0x3f, 0x3d, 0x71, 0x5a, 0x72, 0x0d, 0xde, 0x38, 0x1a,
	0xe9, 0x80, 0x19, 0x9c, 0x06, 0x13, 0x47, 0x3f, 0x78, 0x59, 0x5d, 0x7a, 0x2c, 0xdb, 0x06, 0x78,
	0x37, 0x79, 0x3d, 0x39, 0x3b, 0xa7, 0x53, 0x3f, 0x70, 0x5a, 0xa4, 0x0d, 0xc6, 0xd8, 0xa7, 0x8e,
	0x46, 0x6c, 0xb0, 0xce, 0xa9, 0x3f, 0x0d, 0x1c, 0x9d, 0x74, 0xa1, 0x3d, 0x9a, 0x8e, 0xdf, 0x8f,
	0xdf, 0x4e, 0x1c, 0x63, 0xf4, 0xe2, 0xc3, 0xb3, 0xeb, 0x48, 0xdc, 0x94, 0x97, 0xde, 0x2c, 0x8d,
	0x87, 0xc5, 0x22, 0xe1, 0x39, 0xff, 0x5c, 0xaf, 0x17, 0x6c, 0x9e, 0xdd, 0xb0, 0x21, 0xcb, 0xa2,
	0xe1, 0xfa, 0x63, 0x7b, 0xb9, 0x81, 0xef, 0xec, 0xd1, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f,
	0xdd, 0x29, 0x3c, 0x87, 0x05, 0x00, 0x00,
}
