// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/agent/pedestrian.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/synerex/synerex_alpha/api/simulation/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pedestrian struct {
	Status               *PedStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Route                *PedRoute  `protobuf:"bytes,7,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pedestrian) Reset()         { *m = Pedestrian{} }
func (m *Pedestrian) String() string { return proto.CompactTextString(m) }
func (*Pedestrian) ProtoMessage()    {}
func (*Pedestrian) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fa28333fe02ca, []int{0}
}

func (m *Pedestrian) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pedestrian.Unmarshal(m, b)
}
func (m *Pedestrian) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pedestrian.Marshal(b, m, deterministic)
}
func (m *Pedestrian) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pedestrian.Merge(m, src)
}
func (m *Pedestrian) XXX_Size() int {
	return xxx_messageInfo_Pedestrian.Size(m)
}
func (m *Pedestrian) XXX_DiscardUnknown() {
	xxx_messageInfo_Pedestrian.DiscardUnknown(m)
}

var xxx_messageInfo_Pedestrian proto.InternalMessageInfo

func (m *Pedestrian) GetStatus() *PedStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Pedestrian) GetRoute() *PedRoute {
	if m != nil {
		return m.Route
	}
	return nil
}

type PedRoute struct {
	Position             *common.Coord   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Direction            float64         `protobuf:"fixed64,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                float64         `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Destination          *common.Coord   `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Departure            *common.Coord   `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	TransitPoints        []*common.Coord `protobuf:"bytes,6,rep,name=transit_points,json=transitPoints,proto3" json:"transit_points,omitempty"`
	NextTransit          *common.Coord   `protobuf:"bytes,7,opt,name=next_transit,json=nextTransit,proto3" json:"next_transit,omitempty"`
	TotalDistance        float64         `protobuf:"fixed64,8,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	RequiredTime         float64         `protobuf:"fixed64,9,opt,name=required_time,json=requiredTime,proto3" json:"required_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PedRoute) Reset()         { *m = PedRoute{} }
func (m *PedRoute) String() string { return proto.CompactTextString(m) }
func (*PedRoute) ProtoMessage()    {}
func (*PedRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fa28333fe02ca, []int{1}
}

func (m *PedRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PedRoute.Unmarshal(m, b)
}
func (m *PedRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PedRoute.Marshal(b, m, deterministic)
}
func (m *PedRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PedRoute.Merge(m, src)
}
func (m *PedRoute) XXX_Size() int {
	return xxx_messageInfo_PedRoute.Size(m)
}
func (m *PedRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_PedRoute.DiscardUnknown(m)
}

var xxx_messageInfo_PedRoute proto.InternalMessageInfo

func (m *PedRoute) GetPosition() *common.Coord {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *PedRoute) GetDirection() float64 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *PedRoute) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *PedRoute) GetDestination() *common.Coord {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *PedRoute) GetDeparture() *common.Coord {
	if m != nil {
		return m.Departure
	}
	return nil
}

func (m *PedRoute) GetTransitPoints() []*common.Coord {
	if m != nil {
		return m.TransitPoints
	}
	return nil
}

func (m *PedRoute) GetNextTransit() *common.Coord {
	if m != nil {
		return m.NextTransit
	}
	return nil
}

func (m *PedRoute) GetTotalDistance() float64 {
	if m != nil {
		return m.TotalDistance
	}
	return 0
}

func (m *PedRoute) GetRequiredTime() float64 {
	if m != nil {
		return m.RequiredTime
	}
	return 0
}

type PedStatus struct {
	Age                  string   `protobuf:"bytes,1,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  string   `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PedStatus) Reset()         { *m = PedStatus{} }
func (m *PedStatus) String() string { return proto.CompactTextString(m) }
func (*PedStatus) ProtoMessage()    {}
func (*PedStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a83fa28333fe02ca, []int{2}
}

func (m *PedStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PedStatus.Unmarshal(m, b)
}
func (m *PedStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PedStatus.Marshal(b, m, deterministic)
}
func (m *PedStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PedStatus.Merge(m, src)
}
func (m *PedStatus) XXX_Size() int {
	return xxx_messageInfo_PedStatus.Size(m)
}
func (m *PedStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PedStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PedStatus proto.InternalMessageInfo

func (m *PedStatus) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *PedStatus) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *PedStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Pedestrian)(nil), "api.pedestrian.Pedestrian")
	proto.RegisterType((*PedRoute)(nil), "api.pedestrian.PedRoute")
	proto.RegisterType((*PedStatus)(nil), "api.pedestrian.PedStatus")
}

func init() { proto.RegisterFile("simulation/agent/pedestrian.proto", fileDescriptor_a83fa28333fe02ca) }

var fileDescriptor_a83fa28333fe02ca = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x55, 0xba, 0x2d, 0xcd, 0xec, 0xb6, 0x02, 0x8b, 0x83, 0x41, 0x08, 0x95, 0x22, 0xa4,
	0xbd, 0x90, 0x08, 0x16, 0x04, 0x67, 0x96, 0x07, 0xa8, 0xcc, 0x9e, 0xb8, 0x44, 0xde, 0x7a, 0xd4,
	0xb5, 0xd4, 0xd8, 0xc6, 0x9e, 0x48, 0xe5, 0x29, 0x78, 0x65, 0xe4, 0x69, 0x9a, 0x16, 0x14, 0x4e,
	0x9e, 0xfc, 0xfe, 0xfe, 0xf8, 0xf7, 0x78, 0xe0, 0x75, 0xb2, 0x4d, 0xbb, 0xd3, 0x64, 0xbd, 0xab,
	0xf4, 0x16, 0x1d, 0x55, 0x01, 0x0d, 0x26, 0x8a, 0x56, 0xbb, 0x32, 0x44, 0x4f, 0x5e, 0x2c, 0x74,
	0xb0, 0xe5, 0x49, 0x7d, 0xf1, 0xea, 0xcc, 0xb2, 0xf1, 0x4d, 0xd3, 0x2f, 0x07, 0x7e, 0xe5, 0x01,
	0xd6, 0x3d, 0x2d, 0xde, 0xc3, 0x34, 0x91, 0xa6, 0x36, 0xc9, 0x8b, 0xe5, 0xe8, 0xfa, 0xf2, 0xc3,
	0xf3, 0xf2, 0xef, 0xdf, 0x95, 0x6b, 0x34, 0xdf, 0x19, 0x50, 0x1d, 0x28, 0x4a, 0x98, 0x44, 0xdf,
	0x12, 0xca, 0xc7, 0xec, 0x90, 0x03, 0x0e, 0x95, 0xf7, 0xd5, 0x01, 0x5b, 0xfd, 0x1e, 0xc3, 0xec,
	0xa8, 0x89, 0x77, 0x30, 0x0b, 0x3e, 0xd9, 0x9c, 0x4e, 0x8e, 0xd8, 0xff, 0x94, 0xfd, 0x5d, 0xc4,
	0x5b, 0xef, 0xa3, 0x51, 0x3d, 0x22, 0x5e, 0x42, 0x61, 0x6c, 0xc4, 0x0d, 0xf3, 0x8f, 0x96, 0xa3,
	0xeb, 0x91, 0x3a, 0x09, 0xe2, 0x19, 0x4c, 0x52, 0x40, 0x34, 0x72, 0xcc, 0x3b, 0x87, 0x0f, 0x71,
	0x03, 0x97, 0x39, 0x8b, 0x75, 0xdc, 0x83, 0xee, 0x5e, 0x03, 0xa7, 0x9c, 0x53, 0xa2, 0x82, 0xc2,
	0x60, 0xd0, 0x91, 0xda, 0x88, 0x72, 0xf2, 0x3f, 0xcb, 0x89, 0x11, 0x5f, 0x60, 0x41, 0x51, 0xbb,
	0x64, 0xa9, 0x0e, 0xde, 0x3a, 0x4a, 0x72, 0xba, 0x1c, 0x0f, 0xbb, 0xe6, 0x1d, 0xb8, 0x66, 0x4e,
	0x7c, 0x84, 0x2b, 0x87, 0x7b, 0xaa, 0x3b, 0xb5, 0x6b, 0xe3, 0x50, 0xc0, 0x8c, 0xdd, 0x1d, 0x28,
	0xf1, 0x16, 0x16, 0xe4, 0x49, 0xef, 0x6a, 0x63, 0x13, 0x69, 0xb7, 0x41, 0x39, 0xe3, 0x4b, 0xcf,
	0x59, 0xfd, 0xd6, 0x89, 0xe2, 0x0d, 0xcc, 0x23, 0xfe, 0x6c, 0x6d, 0x44, 0x53, 0x93, 0x6d, 0x50,
	0x16, 0x4c, 0x5d, 0x1d, 0xc5, 0x3b, 0xdb, 0xe0, 0xea, 0x16, 0x8a, 0xfe, 0x59, 0xc5, 0x13, 0x18,
	0xeb, 0x2d, 0xf2, 0x63, 0x14, 0x2a, 0x97, 0x59, 0x49, 0xb8, 0xe7, 0x76, 0x17, 0x2a, 0x97, 0x42,
	0xc0, 0x85, 0xd3, 0x0d, 0x72, 0x9f, 0x0b, 0xc5, 0xf5, 0xd7, 0xcf, 0x3f, 0x3e, 0x6d, 0x2d, 0x3d,
	0xb4, 0xf7, 0x39, 0x74, 0x95, 0x7e, 0x39, 0x8c, 0xb8, 0x3f, 0xae, 0xb5, 0xde, 0x85, 0x07, 0x5d,
	0xe9, 0x60, 0xab, 0x7f, 0x27, 0xf8, 0x7e, 0xca, 0x73, 0x78, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xf9, 0x0b, 0x70, 0x86, 0xdc, 0x02, 0x00, 0x00,
}
