# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rideshare/rideshare.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rideshare/rideshare.proto',
  package='api.rideshare',
  syntax='proto3',
  serialized_options=_b('Z.github.com/synerex/synerex_alpha/api/rideshare'),
  serialized_pb=_b('\n\x19rideshare/rideshare.proto\x12\rapi.rideshare\x1a\x1egoogle/protobuf/duration.proto\x1a\x13\x63ommon/common.proto\"\x8d\x02\n\tRideShare\x12\'\n\x0c\x64\x65part_point\x18\x01 \x01(\x0b\x32\x11.api.common.Place\x12\'\n\x0c\x61rrive_point\x18\x02 \x01(\x0b\x32\x11.api.common.Place\x12%\n\x0b\x64\x65part_time\x18\x03 \x01(\x0b\x32\x10.api.common.Time\x12%\n\x0b\x61rrive_time\x18\x04 \x01(\x0b\x32\x10.api.common.Time\x12\x11\n\tnum_adult\x18\x05 \x01(\r\x12\x11\n\tnum_child\x18\x06 \x01(\r\x12$\n\x06routes\x18\x07 \x03(\x0b\x32\x14.api.rideshare.Route\x12\x14\n\x0c\x61mount_price\x18\x08 \x01(\r\"\xe8\x03\n\x05Route\x12\x30\n\x0ctraffic_type\x18\x01 \x01(\x0e\x32\x1a.api.rideshare.TrafficType\x12.\n\x0bstatus_type\x18\x02 \x01(\x0e\x32\x19.api.rideshare.StatusType\x12\x16\n\x0etransport_name\x18\x03 \x01(\t\x12\x16\n\x0etransport_line\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\x12\'\n\x0c\x64\x65part_point\x18\x06 \x01(\x0b\x32\x11.api.common.Place\x12\'\n\x0c\x61rrive_point\x18\x07 \x01(\x0b\x32\x11.api.common.Place\x12%\n\x0b\x64\x65part_time\x18\x08 \x01(\x0b\x32\x10.api.common.Time\x12%\n\x0b\x61rrive_time\x18\t \x01(\x0b\x32\x10.api.common.Time\x12.\n\x0b\x61mount_time\x18\n \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0c\x61mount_price\x18\x0b \x01(\r\x12\x15\n\ramount_sheets\x18\x0c \x01(\r\x12\x18\n\x10\x61vailable_sheets\x18\r \x01(\r\x12!\n\x06points\x18\x0f \x03(\x0b\x32\x11.api.common.Point*+\n\x0bTrafficType\x12\x08\n\x04TAXI\x10\x00\x12\x07\n\x03\x42US\x10\x01\x12\t\n\x05TRAIN\x10\x02*6\n\nStatusType\x12\x08\n\x04\x46REE\x10\x00\x12\n\n\x06PICKUP\x10\x01\x12\x08\n\x04RIDE\x10\x02\x12\x08\n\x04\x46ULL\x10\x03\x42\x30Z.github.com/synerex/synerex_alpha/api/rideshareb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,common_dot_common__pb2.DESCRIPTOR,])

_TRAFFICTYPE = _descriptor.EnumDescriptor(
  name='TrafficType',
  full_name='api.rideshare.TrafficType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TAXI', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRAIN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=860,
  serialized_end=903,
)
_sym_db.RegisterEnumDescriptor(_TRAFFICTYPE)

TrafficType = enum_type_wrapper.EnumTypeWrapper(_TRAFFICTYPE)
_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='api.rideshare.StatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FREE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PICKUP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIDE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FULL', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=905,
  serialized_end=959,
)
_sym_db.RegisterEnumDescriptor(_STATUSTYPE)

StatusType = enum_type_wrapper.EnumTypeWrapper(_STATUSTYPE)
TAXI = 0
BUS = 1
TRAIN = 2
FREE = 0
PICKUP = 1
RIDE = 2
FULL = 3



_RIDESHARE = _descriptor.Descriptor(
  name='RideShare',
  full_name='api.rideshare.RideShare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depart_point', full_name='api.rideshare.RideShare.depart_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_point', full_name='api.rideshare.RideShare.arrive_point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depart_time', full_name='api.rideshare.RideShare.depart_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_time', full_name='api.rideshare.RideShare.arrive_time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_adult', full_name='api.rideshare.RideShare.num_adult', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_child', full_name='api.rideshare.RideShare.num_child', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='routes', full_name='api.rideshare.RideShare.routes', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_price', full_name='api.rideshare.RideShare.amount_price', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=367,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='api.rideshare.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traffic_type', full_name='api.rideshare.Route.traffic_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_type', full_name='api.rideshare.Route.status_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transport_name', full_name='api.rideshare.Route.transport_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transport_line', full_name='api.rideshare.Route.transport_line', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='api.rideshare.Route.destination', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depart_point', full_name='api.rideshare.Route.depart_point', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_point', full_name='api.rideshare.Route.arrive_point', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depart_time', full_name='api.rideshare.Route.depart_time', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_time', full_name='api.rideshare.Route.arrive_time', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_time', full_name='api.rideshare.Route.amount_time', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_price', full_name='api.rideshare.Route.amount_price', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_sheets', full_name='api.rideshare.Route.amount_sheets', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='available_sheets', full_name='api.rideshare.Route.available_sheets', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='api.rideshare.Route.points', index=13,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=858,
)

_RIDESHARE.fields_by_name['depart_point'].message_type = common_dot_common__pb2._PLACE
_RIDESHARE.fields_by_name['arrive_point'].message_type = common_dot_common__pb2._PLACE
_RIDESHARE.fields_by_name['depart_time'].message_type = common_dot_common__pb2._TIME
_RIDESHARE.fields_by_name['arrive_time'].message_type = common_dot_common__pb2._TIME
_RIDESHARE.fields_by_name['routes'].message_type = _ROUTE
_ROUTE.fields_by_name['traffic_type'].enum_type = _TRAFFICTYPE
_ROUTE.fields_by_name['status_type'].enum_type = _STATUSTYPE
_ROUTE.fields_by_name['depart_point'].message_type = common_dot_common__pb2._PLACE
_ROUTE.fields_by_name['arrive_point'].message_type = common_dot_common__pb2._PLACE
_ROUTE.fields_by_name['depart_time'].message_type = common_dot_common__pb2._TIME
_ROUTE.fields_by_name['arrive_time'].message_type = common_dot_common__pb2._TIME
_ROUTE.fields_by_name['amount_time'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_ROUTE.fields_by_name['points'].message_type = common_dot_common__pb2._POINT
DESCRIPTOR.message_types_by_name['RideShare'] = _RIDESHARE
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.enum_types_by_name['TrafficType'] = _TRAFFICTYPE
DESCRIPTOR.enum_types_by_name['StatusType'] = _STATUSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RideShare = _reflection.GeneratedProtocolMessageType('RideShare', (_message.Message,), {
  'DESCRIPTOR' : _RIDESHARE,
  '__module__' : 'rideshare.rideshare_pb2'
  # @@protoc_insertion_point(class_scope:api.rideshare.RideShare)
  })
_sym_db.RegisterMessage(RideShare)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), {
  'DESCRIPTOR' : _ROUTE,
  '__module__' : 'rideshare.rideshare_pb2'
  # @@protoc_insertion_point(class_scope:api.rideshare.Route)
  })
_sym_db.RegisterMessage(Route)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
