// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentType int32

const (
	AgentType_PEDESTRIAN AgentType = 0
	AgentType_CAR        AgentType = 1
	AgentType_TRAIN      AgentType = 2
	AgentType_SIGNAL     AgentType = 3
)

var AgentType_name = map[int32]string{
	0: "PEDESTRIAN",
	1: "CAR",
	2: "TRAIN",
	3: "SIGNAL",
}

var AgentType_value = map[string]int32{
	"PEDESTRIAN": 0,
	"CAR":        1,
	"TRAIN":      2,
	"SIGNAL":     3,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c0af95f0c847945a, []int{0}
}

type Coord struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0af95f0c847945a, []int{0}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coord) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.common.AgentType", AgentType_name, AgentType_value)
	proto.RegisterType((*Coord)(nil), "api.common.Coord")
}

func init() { proto.RegisterFile("simulation/common/common.proto", fileDescriptor_c0af95f0c847945a) }

var fileDescriptor_c0af95f0c847945a = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0xce, 0xcc, 0x2d,
	0xcd, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x4f, 0xce, 0xcf, 0xcd, 0x85, 0x53, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x5c, 0x89, 0x05, 0x99, 0x7a, 0x10, 0x11, 0x25, 0x47, 0x2e, 0x56, 0xe7,
	0xfc, 0xfc, 0xa2, 0x14, 0x21, 0x29, 0x2e, 0x0e, 0x90, 0x96, 0x92, 0xd2, 0x94, 0x54, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xc6, 0x20, 0x38, 0x5f, 0x48, 0x86, 0x8b, 0x33, 0x27, 0x3f, 0x2f, 0x1d, 0x22,
	0xc9, 0x04, 0x96, 0x44, 0x08, 0x68, 0x59, 0x73, 0x71, 0x3a, 0xa6, 0xa7, 0xe6, 0x95, 0x84, 0x54,
	0x16, 0xa4, 0x0a, 0xf1, 0x71, 0x71, 0x05, 0xb8, 0xba, 0xb8, 0x06, 0x87, 0x04, 0x79, 0x3a, 0xfa,
	0x09, 0x30, 0x08, 0xb1, 0x73, 0x31, 0x3b, 0x3b, 0x06, 0x09, 0x30, 0x0a, 0x71, 0x72, 0xb1, 0x86,
	0x04, 0x39, 0x7a, 0xfa, 0x09, 0x30, 0x09, 0x71, 0x71, 0xb1, 0x05, 0x7b, 0xba, 0xfb, 0x39, 0xfa,
	0x08, 0x30, 0x3b, 0x59, 0x44, 0x99, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0x81, 0x1c, 0xa4, 0x5f,
	0x5c, 0x99, 0x97, 0x5a, 0x94, 0x5a, 0x01, 0xa3, 0xe3, 0x13, 0x73, 0x0a, 0x32, 0x12, 0xf5, 0x13,
	0x0b, 0x32, 0xf5, 0x31, 0xbc, 0x94, 0xc4, 0x06, 0xf6, 0x8c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x7f, 0x96, 0x84, 0x30, 0xee, 0x00, 0x00, 0x00,
}
