// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpa/meeting.proto

package rpa // import "github.com/synerex/synerex_alpha/api/rpa"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MeetingService struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Year                 string   `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	Month                string   `protobuf:"bytes,4,opt,name=month,proto3" json:"month,omitempty"`
	Day                  string   `protobuf:"bytes,5,opt,name=day,proto3" json:"day,omitempty"`
	Week                 string   `protobuf:"bytes,6,opt,name=week,proto3" json:"week,omitempty"`
	Start                string   `protobuf:"bytes,7,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,8,opt,name=end,proto3" json:"end,omitempty"`
	People               string   `protobuf:"bytes,9,opt,name=people,proto3" json:"people,omitempty"`
	Title                string   `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	Room                 string   `protobuf:"bytes,11,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeetingService) Reset()         { *m = MeetingService{} }
func (m *MeetingService) String() string { return proto.CompactTextString(m) }
func (*MeetingService) ProtoMessage()    {}
func (*MeetingService) Descriptor() ([]byte, []int) {
	return fileDescriptor_meeting_25ce26ff901acfee, []int{0}
}
func (m *MeetingService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingService.Unmarshal(m, b)
}
func (m *MeetingService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingService.Marshal(b, m, deterministic)
}
func (dst *MeetingService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingService.Merge(dst, src)
}
func (m *MeetingService) XXX_Size() int {
	return xxx_messageInfo_MeetingService.Size(m)
}
func (m *MeetingService) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingService.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingService proto.InternalMessageInfo

func (m *MeetingService) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *MeetingService) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MeetingService) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *MeetingService) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

func (m *MeetingService) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *MeetingService) GetWeek() string {
	if m != nil {
		return m.Week
	}
	return ""
}

func (m *MeetingService) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *MeetingService) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *MeetingService) GetPeople() string {
	if m != nil {
		return m.People
	}
	return ""
}

func (m *MeetingService) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MeetingService) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func init() {
	proto.RegisterType((*MeetingService)(nil), "api.meeting.MeetingService")
}

func init() { proto.RegisterFile("rpa/meeting.proto", fileDescriptor_meeting_25ce26ff901acfee) }

var fileDescriptor_meeting_25ce26ff901acfee = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0xda, 0x06, 0xea, 0x4a, 0x08, 0x2c, 0x84, 0x6e, 0x44, 0x4c, 0x15, 0x43, 0x32,
	0xf0, 0x06, 0xec, 0x2c, 0xb0, 0xb1, 0xa0, 0x6b, 0x72, 0x6a, 0x2c, 0x12, 0xdb, 0x72, 0xae, 0x80,
	0xdf, 0x9b, 0x07, 0x40, 0xe7, 0x4b, 0x27, 0xff, 0xdf, 0x2f, 0x7d, 0x77, 0x27, 0x9b, 0xdb, 0x14,
	0xb1, 0x9d, 0x88, 0xd8, 0xf9, 0x63, 0x13, 0x53, 0xe0, 0x60, 0x77, 0x18, 0x5d, 0xb3, 0x54, 0x8f,
	0x7f, 0x95, 0xb9, 0x7e, 0xd5, 0xfc, 0x4e, 0xe9, 0xdb, 0x75, 0x64, 0x6f, 0xcc, 0xaa, 0x73, 0x3d,
	0x54, 0x0f, 0xd5, 0x7e, 0xfb, 0x26, 0xd1, 0xde, 0x9b, 0x7a, 0x66, 0xe4, 0xd3, 0x0c, 0x17, 0xa5,
	0x5c, 0xc8, 0x5a, 0xb3, 0xce, 0x84, 0x09, 0x56, 0xa5, 0x2d, 0xd9, 0xde, 0x99, 0xcd, 0x14, 0x3c,
	0x0f, 0xb0, 0x2e, 0xa5, 0x82, 0xcc, 0xec, 0x31, 0xc3, 0x46, 0x67, 0xf6, 0x98, 0xc5, 0xfd, 0x21,
	0xfa, 0x82, 0x5a, 0x5d, 0xc9, 0xe2, 0xce, 0x8c, 0x89, 0xe1, 0x52, 0xdd, 0x02, 0xe2, 0x92, 0xef,
	0xe1, 0x4a, 0x5d, 0xf2, 0xe5, 0x9e, 0x48, 0x21, 0x8e, 0x04, 0x5b, 0xbd, 0x47, 0x49, 0x7c, 0x76,
	0x3c, 0x12, 0x18, 0xf5, 0x0b, 0xc8, 0xa6, 0x14, 0xc2, 0x04, 0x3b, 0xdd, 0x24, 0xf9, 0xe5, 0xe9,
	0x63, 0x7f, 0x74, 0x3c, 0x9c, 0x0e, 0x4d, 0x17, 0xa6, 0x76, 0xce, 0x9e, 0x12, 0xfd, 0x9e, 0xdf,
	0x4f, 0x1c, 0xe3, 0x80, 0x2d, 0x46, 0xd7, 0xa6, 0x88, 0x87, 0xba, 0x7c, 0xdb, 0xf3, 0x7f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x54, 0x6b, 0x12, 0x5a, 0x4b, 0x01, 0x00, 0x00,
}
