// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/synerex/synerex.proto

package synerex

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	agent "github.com/synerex/synerex_alpha/api/simulation/agent"
	area "github.com/synerex/synerex_alpha/api/simulation/area"
	clock "github.com/synerex/synerex_alpha/api/simulation/clock"
	participant "github.com/synerex/synerex_alpha/api/simulation/participant"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusType int32

const (
	StatusType_OK   StatusType = 0
	StatusType_NG   StatusType = 1
	StatusType_NONE StatusType = 2
)

var StatusType_name = map[int32]string{
	0: "OK",
	1: "NG",
	2: "NONE",
}

var StatusType_value = map[string]int32{
	"OK":   0,
	"NG":   1,
	"NONE": 2,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_81d77a6394be03b4, []int{0}
}

type DemandType int32

const (
	DemandType_GET_AGENTS_DEMAND       DemandType = 0
	DemandType_SET_AGENTS_DEMAND       DemandType = 1
	DemandType_GET_AGENTS_ROUTE_DEMAND DemandType = 2
	DemandType_SET_AGENTS_ROUTE_DEMAND DemandType = 3
	DemandType_GET_AREA_DEMAND         DemandType = 4
	DemandType_GET_PARTICIPANT_DEMAND  DemandType = 5
	DemandType_SET_PARTICIPANT_DEMAND  DemandType = 6
	DemandType_SET_CLOCK_DEMAND        DemandType = 7
	DemandType_FORWARD_CLOCK_DEMAND    DemandType = 8
	DemandType_BACK_CLOCK_DEMAND       DemandType = 9
)

var DemandType_name = map[int32]string{
	0: "GET_AGENTS_DEMAND",
	1: "SET_AGENTS_DEMAND",
	2: "GET_AGENTS_ROUTE_DEMAND",
	3: "SET_AGENTS_ROUTE_DEMAND",
	4: "GET_AREA_DEMAND",
	5: "GET_PARTICIPANT_DEMAND",
	6: "SET_PARTICIPANT_DEMAND",
	7: "SET_CLOCK_DEMAND",
	8: "FORWARD_CLOCK_DEMAND",
	9: "BACK_CLOCK_DEMAND",
}

var DemandType_value = map[string]int32{
	"GET_AGENTS_DEMAND":       0,
	"SET_AGENTS_DEMAND":       1,
	"GET_AGENTS_ROUTE_DEMAND": 2,
	"SET_AGENTS_ROUTE_DEMAND": 3,
	"GET_AREA_DEMAND":         4,
	"GET_PARTICIPANT_DEMAND":  5,
	"SET_PARTICIPANT_DEMAND":  6,
	"SET_CLOCK_DEMAND":        7,
	"FORWARD_CLOCK_DEMAND":    8,
	"BACK_CLOCK_DEMAND":       9,
}

func (x DemandType) String() string {
	return proto.EnumName(DemandType_name, int32(x))
}

func (DemandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_81d77a6394be03b4, []int{1}
}

type SupplyType int32

const (
	SupplyType_GET_AGENTS_SUPPLY       SupplyType = 0
	SupplyType_SET_AGENTS_SUPPLY       SupplyType = 1
	SupplyType_FORWARD_AGENTS_SUPPLY   SupplyType = 2
	SupplyType_GET_AGENTS_ROUTE_SUPPLY SupplyType = 3
	SupplyType_SET_AGENTS_ROUTE_SUPPLY SupplyType = 4
	SupplyType_GET_AREA_SUPPLY         SupplyType = 5
	SupplyType_GET_PARTICIPANT_SUPPLY  SupplyType = 6
	SupplyType_SET_PARTICIPANT_SUPPLY  SupplyType = 7
	SupplyType_SET_CLOCK_SUPPLY        SupplyType = 8
	SupplyType_FORWARD_CLOCK_SUPPLY    SupplyType = 9
	SupplyType_BACK_CLOCK_SUPPLY       SupplyType = 10
)

var SupplyType_name = map[int32]string{
	0:  "GET_AGENTS_SUPPLY",
	1:  "SET_AGENTS_SUPPLY",
	2:  "FORWARD_AGENTS_SUPPLY",
	3:  "GET_AGENTS_ROUTE_SUPPLY",
	4:  "SET_AGENTS_ROUTE_SUPPLY",
	5:  "GET_AREA_SUPPLY",
	6:  "GET_PARTICIPANT_SUPPLY",
	7:  "SET_PARTICIPANT_SUPPLY",
	8:  "SET_CLOCK_SUPPLY",
	9:  "FORWARD_CLOCK_SUPPLY",
	10: "BACK_CLOCK_SUPPLY",
}

var SupplyType_value = map[string]int32{
	"GET_AGENTS_SUPPLY":       0,
	"SET_AGENTS_SUPPLY":       1,
	"FORWARD_AGENTS_SUPPLY":   2,
	"GET_AGENTS_ROUTE_SUPPLY": 3,
	"SET_AGENTS_ROUTE_SUPPLY": 4,
	"GET_AREA_SUPPLY":         5,
	"GET_PARTICIPANT_SUPPLY":  6,
	"SET_PARTICIPANT_SUPPLY":  7,
	"SET_CLOCK_SUPPLY":        8,
	"FORWARD_CLOCK_SUPPLY":    9,
	"BACK_CLOCK_SUPPLY":       10,
}

func (x SupplyType) String() string {
	return proto.EnumName(SupplyType_name, int32(x))
}

func (SupplyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_81d77a6394be03b4, []int{2}
}

type SimDemand struct {
	// participant info
	DemandType DemandType `protobuf:"varint,1,opt,name=demand_type,json=demandType,proto3,enum=api.synerex.DemandType" json:"demand_type,omitempty"`
	// meta data
	StatusType StatusType `protobuf:"varint,2,opt,name=status_type,json=statusType,proto3,enum=api.synerex.StatusType" json:"status_type,omitempty"`
	Meta       string     `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	// demand data
	//
	// Types that are valid to be assigned to Data:
	//	*SimDemand_GetAgentsDemand
	//	*SimDemand_SetAgentsDemand
	//	*SimDemand_GetAgentRouteDemand
	//	*SimDemand_GetAgentsRouteDemand
	//	*SimDemand_GetAreaDemand
	//	*SimDemand_GetParticipantDemand
	//	*SimDemand_SetParticipantDemand
	//	*SimDemand_SetClockDemand
	//	*SimDemand_ForwardClockDemand
	//	*SimDemand_BackClockDemand
	Data                 isSimDemand_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimDemand) Reset()         { *m = SimDemand{} }
func (m *SimDemand) String() string { return proto.CompactTextString(m) }
func (*SimDemand) ProtoMessage()    {}
func (*SimDemand) Descriptor() ([]byte, []int) {
	return fileDescriptor_81d77a6394be03b4, []int{0}
}

func (m *SimDemand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimDemand.Unmarshal(m, b)
}
func (m *SimDemand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimDemand.Marshal(b, m, deterministic)
}
func (m *SimDemand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimDemand.Merge(m, src)
}
func (m *SimDemand) XXX_Size() int {
	return xxx_messageInfo_SimDemand.Size(m)
}
func (m *SimDemand) XXX_DiscardUnknown() {
	xxx_messageInfo_SimDemand.DiscardUnknown(m)
}

var xxx_messageInfo_SimDemand proto.InternalMessageInfo

func (m *SimDemand) GetDemandType() DemandType {
	if m != nil {
		return m.DemandType
	}
	return DemandType_GET_AGENTS_DEMAND
}

func (m *SimDemand) GetStatusType() StatusType {
	if m != nil {
		return m.StatusType
	}
	return StatusType_OK
}

func (m *SimDemand) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type isSimDemand_Data interface {
	isSimDemand_Data()
}

type SimDemand_GetAgentsDemand struct {
	GetAgentsDemand *agent.GetAgentsDemand `protobuf:"bytes,4,opt,name=get_agents_demand,json=getAgentsDemand,proto3,oneof"`
}

type SimDemand_SetAgentsDemand struct {
	SetAgentsDemand *agent.SetAgentsDemand `protobuf:"bytes,5,opt,name=set_agents_demand,json=setAgentsDemand,proto3,oneof"`
}

type SimDemand_GetAgentRouteDemand struct {
	GetAgentRouteDemand *agent.GetAgentRouteDemand `protobuf:"bytes,6,opt,name=get_agent_route_demand,json=getAgentRouteDemand,proto3,oneof"`
}

type SimDemand_GetAgentsRouteDemand struct {
	GetAgentsRouteDemand *agent.GetAgentsRouteDemand `protobuf:"bytes,7,opt,name=get_agents_route_demand,json=getAgentsRouteDemand,proto3,oneof"`
}

type SimDemand_GetAreaDemand struct {
	GetAreaDemand *area.GetAreaDemand `protobuf:"bytes,8,opt,name=get_area_demand,json=getAreaDemand,proto3,oneof"`
}

type SimDemand_GetParticipantDemand struct {
	GetParticipantDemand *participant.GetParticipantDemand `protobuf:"bytes,9,opt,name=get_participant_demand,json=getParticipantDemand,proto3,oneof"`
}

type SimDemand_SetParticipantDemand struct {
	SetParticipantDemand *participant.SetParticipantDemand `protobuf:"bytes,10,opt,name=set_participant_demand,json=setParticipantDemand,proto3,oneof"`
}

type SimDemand_SetClockDemand struct {
	SetClockDemand *clock.SetClockDemand `protobuf:"bytes,11,opt,name=set_clock_demand,json=setClockDemand,proto3,oneof"`
}

type SimDemand_ForwardClockDemand struct {
	ForwardClockDemand *clock.ForwardClockDemand `protobuf:"bytes,12,opt,name=forward_clock_demand,json=forwardClockDemand,proto3,oneof"`
}

type SimDemand_BackClockDemand struct {
	BackClockDemand *clock.BackClockDemand `protobuf:"bytes,13,opt,name=back_clock_demand,json=backClockDemand,proto3,oneof"`
}

func (*SimDemand_GetAgentsDemand) isSimDemand_Data() {}

func (*SimDemand_SetAgentsDemand) isSimDemand_Data() {}

func (*SimDemand_GetAgentRouteDemand) isSimDemand_Data() {}

func (*SimDemand_GetAgentsRouteDemand) isSimDemand_Data() {}

func (*SimDemand_GetAreaDemand) isSimDemand_Data() {}

func (*SimDemand_GetParticipantDemand) isSimDemand_Data() {}

func (*SimDemand_SetParticipantDemand) isSimDemand_Data() {}

func (*SimDemand_SetClockDemand) isSimDemand_Data() {}

func (*SimDemand_ForwardClockDemand) isSimDemand_Data() {}

func (*SimDemand_BackClockDemand) isSimDemand_Data() {}

func (m *SimDemand) GetData() isSimDemand_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SimDemand) GetGetAgentsDemand() *agent.GetAgentsDemand {
	if x, ok := m.GetData().(*SimDemand_GetAgentsDemand); ok {
		return x.GetAgentsDemand
	}
	return nil
}

func (m *SimDemand) GetSetAgentsDemand() *agent.SetAgentsDemand {
	if x, ok := m.GetData().(*SimDemand_SetAgentsDemand); ok {
		return x.SetAgentsDemand
	}
	return nil
}

func (m *SimDemand) GetGetAgentRouteDemand() *agent.GetAgentRouteDemand {
	if x, ok := m.GetData().(*SimDemand_GetAgentRouteDemand); ok {
		return x.GetAgentRouteDemand
	}
	return nil
}

func (m *SimDemand) GetGetAgentsRouteDemand() *agent.GetAgentsRouteDemand {
	if x, ok := m.GetData().(*SimDemand_GetAgentsRouteDemand); ok {
		return x.GetAgentsRouteDemand
	}
	return nil
}

func (m *SimDemand) GetGetAreaDemand() *area.GetAreaDemand {
	if x, ok := m.GetData().(*SimDemand_GetAreaDemand); ok {
		return x.GetAreaDemand
	}
	return nil
}

func (m *SimDemand) GetGetParticipantDemand() *participant.GetParticipantDemand {
	if x, ok := m.GetData().(*SimDemand_GetParticipantDemand); ok {
		return x.GetParticipantDemand
	}
	return nil
}

func (m *SimDemand) GetSetParticipantDemand() *participant.SetParticipantDemand {
	if x, ok := m.GetData().(*SimDemand_SetParticipantDemand); ok {
		return x.SetParticipantDemand
	}
	return nil
}

func (m *SimDemand) GetSetClockDemand() *clock.SetClockDemand {
	if x, ok := m.GetData().(*SimDemand_SetClockDemand); ok {
		return x.SetClockDemand
	}
	return nil
}

func (m *SimDemand) GetForwardClockDemand() *clock.ForwardClockDemand {
	if x, ok := m.GetData().(*SimDemand_ForwardClockDemand); ok {
		return x.ForwardClockDemand
	}
	return nil
}

func (m *SimDemand) GetBackClockDemand() *clock.BackClockDemand {
	if x, ok := m.GetData().(*SimDemand_BackClockDemand); ok {
		return x.BackClockDemand
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SimDemand) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SimDemand_GetAgentsDemand)(nil),
		(*SimDemand_SetAgentsDemand)(nil),
		(*SimDemand_GetAgentRouteDemand)(nil),
		(*SimDemand_GetAgentsRouteDemand)(nil),
		(*SimDemand_GetAreaDemand)(nil),
		(*SimDemand_GetParticipantDemand)(nil),
		(*SimDemand_SetParticipantDemand)(nil),
		(*SimDemand_SetClockDemand)(nil),
		(*SimDemand_ForwardClockDemand)(nil),
		(*SimDemand_BackClockDemand)(nil),
	}
}

type SimSupply struct {
	// demand type
	SupplyType SupplyType `protobuf:"varint,1,opt,name=supply_type,json=supplyType,proto3,enum=api.synerex.SupplyType" json:"supply_type,omitempty"`
	// meta data
	StatusType StatusType `protobuf:"varint,2,opt,name=status_type,json=statusType,proto3,enum=api.synerex.StatusType" json:"status_type,omitempty"`
	Meta       string     `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	// supply data
	//
	// Types that are valid to be assigned to Data:
	//	*SimSupply_GetAgentsSupply
	//	*SimSupply_SetAgentsSupply
	//	*SimSupply_ForwardAgentsSupply
	//	*SimSupply_GetAgentRouteSupply
	//	*SimSupply_GetAgentsRouteSupply
	//	*SimSupply_GetAreaSupply
	//	*SimSupply_GetParticipantSupply
	//	*SimSupply_SetParticipantSupply
	//	*SimSupply_SetClockSupply
	//	*SimSupply_ForwardClockSupply
	//	*SimSupply_BackClockSupply
	Data                 isSimSupply_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimSupply) Reset()         { *m = SimSupply{} }
func (m *SimSupply) String() string { return proto.CompactTextString(m) }
func (*SimSupply) ProtoMessage()    {}
func (*SimSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_81d77a6394be03b4, []int{1}
}

func (m *SimSupply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimSupply.Unmarshal(m, b)
}
func (m *SimSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimSupply.Marshal(b, m, deterministic)
}
func (m *SimSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimSupply.Merge(m, src)
}
func (m *SimSupply) XXX_Size() int {
	return xxx_messageInfo_SimSupply.Size(m)
}
func (m *SimSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_SimSupply.DiscardUnknown(m)
}

var xxx_messageInfo_SimSupply proto.InternalMessageInfo

func (m *SimSupply) GetSupplyType() SupplyType {
	if m != nil {
		return m.SupplyType
	}
	return SupplyType_GET_AGENTS_SUPPLY
}

func (m *SimSupply) GetStatusType() StatusType {
	if m != nil {
		return m.StatusType
	}
	return StatusType_OK
}

func (m *SimSupply) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type isSimSupply_Data interface {
	isSimSupply_Data()
}

type SimSupply_GetAgentsSupply struct {
	GetAgentsSupply *agent.GetAgentsSupply `protobuf:"bytes,4,opt,name=get_agents_supply,json=getAgentsSupply,proto3,oneof"`
}

type SimSupply_SetAgentsSupply struct {
	SetAgentsSupply *agent.SetAgentsSupply `protobuf:"bytes,5,opt,name=set_agents_supply,json=setAgentsSupply,proto3,oneof"`
}

type SimSupply_ForwardAgentsSupply struct {
	ForwardAgentsSupply *agent.ForwardAgentsSupply `protobuf:"bytes,6,opt,name=forward_agents_supply,json=forwardAgentsSupply,proto3,oneof"`
}

type SimSupply_GetAgentRouteSupply struct {
	GetAgentRouteSupply *agent.GetAgentRouteSupply `protobuf:"bytes,7,opt,name=get_agent_route_supply,json=getAgentRouteSupply,proto3,oneof"`
}

type SimSupply_GetAgentsRouteSupply struct {
	GetAgentsRouteSupply *agent.GetAgentsRouteSupply `protobuf:"bytes,8,opt,name=get_agents_route_supply,json=getAgentsRouteSupply,proto3,oneof"`
}

type SimSupply_GetAreaSupply struct {
	GetAreaSupply *area.GetAreaSupply `protobuf:"bytes,9,opt,name=get_area_supply,json=getAreaSupply,proto3,oneof"`
}

type SimSupply_GetParticipantSupply struct {
	GetParticipantSupply *participant.GetParticipantSupply `protobuf:"bytes,10,opt,name=get_participant_supply,json=getParticipantSupply,proto3,oneof"`
}

type SimSupply_SetParticipantSupply struct {
	SetParticipantSupply *participant.SetParticipantSupply `protobuf:"bytes,11,opt,name=set_participant_supply,json=setParticipantSupply,proto3,oneof"`
}

type SimSupply_SetClockSupply struct {
	SetClockSupply *clock.SetClockSupply `protobuf:"bytes,12,opt,name=set_clock_supply,json=setClockSupply,proto3,oneof"`
}

type SimSupply_ForwardClockSupply struct {
	ForwardClockSupply *clock.ForwardClockSupply `protobuf:"bytes,13,opt,name=forward_clock_supply,json=forwardClockSupply,proto3,oneof"`
}

type SimSupply_BackClockSupply struct {
	BackClockSupply *clock.BackClockSupply `protobuf:"bytes,14,opt,name=back_clock_supply,json=backClockSupply,proto3,oneof"`
}

func (*SimSupply_GetAgentsSupply) isSimSupply_Data() {}

func (*SimSupply_SetAgentsSupply) isSimSupply_Data() {}

func (*SimSupply_ForwardAgentsSupply) isSimSupply_Data() {}

func (*SimSupply_GetAgentRouteSupply) isSimSupply_Data() {}

func (*SimSupply_GetAgentsRouteSupply) isSimSupply_Data() {}

func (*SimSupply_GetAreaSupply) isSimSupply_Data() {}

func (*SimSupply_GetParticipantSupply) isSimSupply_Data() {}

func (*SimSupply_SetParticipantSupply) isSimSupply_Data() {}

func (*SimSupply_SetClockSupply) isSimSupply_Data() {}

func (*SimSupply_ForwardClockSupply) isSimSupply_Data() {}

func (*SimSupply_BackClockSupply) isSimSupply_Data() {}

func (m *SimSupply) GetData() isSimSupply_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SimSupply) GetGetAgentsSupply() *agent.GetAgentsSupply {
	if x, ok := m.GetData().(*SimSupply_GetAgentsSupply); ok {
		return x.GetAgentsSupply
	}
	return nil
}

func (m *SimSupply) GetSetAgentsSupply() *agent.SetAgentsSupply {
	if x, ok := m.GetData().(*SimSupply_SetAgentsSupply); ok {
		return x.SetAgentsSupply
	}
	return nil
}

func (m *SimSupply) GetForwardAgentsSupply() *agent.ForwardAgentsSupply {
	if x, ok := m.GetData().(*SimSupply_ForwardAgentsSupply); ok {
		return x.ForwardAgentsSupply
	}
	return nil
}

func (m *SimSupply) GetGetAgentRouteSupply() *agent.GetAgentRouteSupply {
	if x, ok := m.GetData().(*SimSupply_GetAgentRouteSupply); ok {
		return x.GetAgentRouteSupply
	}
	return nil
}

func (m *SimSupply) GetGetAgentsRouteSupply() *agent.GetAgentsRouteSupply {
	if x, ok := m.GetData().(*SimSupply_GetAgentsRouteSupply); ok {
		return x.GetAgentsRouteSupply
	}
	return nil
}

func (m *SimSupply) GetGetAreaSupply() *area.GetAreaSupply {
	if x, ok := m.GetData().(*SimSupply_GetAreaSupply); ok {
		return x.GetAreaSupply
	}
	return nil
}

func (m *SimSupply) GetGetParticipantSupply() *participant.GetParticipantSupply {
	if x, ok := m.GetData().(*SimSupply_GetParticipantSupply); ok {
		return x.GetParticipantSupply
	}
	return nil
}

func (m *SimSupply) GetSetParticipantSupply() *participant.SetParticipantSupply {
	if x, ok := m.GetData().(*SimSupply_SetParticipantSupply); ok {
		return x.SetParticipantSupply
	}
	return nil
}

func (m *SimSupply) GetSetClockSupply() *clock.SetClockSupply {
	if x, ok := m.GetData().(*SimSupply_SetClockSupply); ok {
		return x.SetClockSupply
	}
	return nil
}

func (m *SimSupply) GetForwardClockSupply() *clock.ForwardClockSupply {
	if x, ok := m.GetData().(*SimSupply_ForwardClockSupply); ok {
		return x.ForwardClockSupply
	}
	return nil
}

func (m *SimSupply) GetBackClockSupply() *clock.BackClockSupply {
	if x, ok := m.GetData().(*SimSupply_BackClockSupply); ok {
		return x.BackClockSupply
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SimSupply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SimSupply_GetAgentsSupply)(nil),
		(*SimSupply_SetAgentsSupply)(nil),
		(*SimSupply_ForwardAgentsSupply)(nil),
		(*SimSupply_GetAgentRouteSupply)(nil),
		(*SimSupply_GetAgentsRouteSupply)(nil),
		(*SimSupply_GetAreaSupply)(nil),
		(*SimSupply_GetParticipantSupply)(nil),
		(*SimSupply_SetParticipantSupply)(nil),
		(*SimSupply_SetClockSupply)(nil),
		(*SimSupply_ForwardClockSupply)(nil),
		(*SimSupply_BackClockSupply)(nil),
	}
}

func init() {
	proto.RegisterEnum("api.synerex.StatusType", StatusType_name, StatusType_value)
	proto.RegisterEnum("api.synerex.DemandType", DemandType_name, DemandType_value)
	proto.RegisterEnum("api.synerex.SupplyType", SupplyType_name, SupplyType_value)
	proto.RegisterType((*SimDemand)(nil), "api.synerex.SimDemand")
	proto.RegisterType((*SimSupply)(nil), "api.synerex.SimSupply")
}

func init() { proto.RegisterFile("simulation/synerex/synerex.proto", fileDescriptor_81d77a6394be03b4) }

var fileDescriptor_81d77a6394be03b4 = []byte{
	// 862 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xdb, 0x6e, 0xe2, 0x38,
	0x18, 0xc7, 0x0b, 0xa5, 0x1c, 0x3e, 0xda, 0x42, 0x5d, 0xda, 0x52, 0xf6, 0x84, 0x2a, 0xed, 0x0a,
	0xf5, 0x82, 0x4a, 0xdd, 0x8b, 0xdd, 0xbd, 0x0c, 0x87, 0xd2, 0xaa, 0x5d, 0x60, 0x13, 0xaa, 0x9d,
	0x19, 0x69, 0x84, 0x0c, 0xa4, 0x69, 0x54, 0x0e, 0x51, 0x62, 0x34, 0xc3, 0x1b, 0xcc, 0x3b, 0xcc,
	0xe5, 0x3c, 0xcb, 0xbc, 0xd7, 0x28, 0xb6, 0x73, 0x30, 0x36, 0x4c, 0x6f, 0xe6, 0x26, 0xb8, 0xff,
	0xbf, 0xfd, 0x8b, 0xf3, 0xc5, 0xdf, 0xbf, 0x81, 0xaa, 0x67, 0xcf, 0x96, 0x53, 0x4c, 0xec, 0xc5,
	0xfc, 0xca, 0x5b, 0xcd, 0x4d, 0xd7, 0xfc, 0x18, 0xfc, 0xd6, 0x1d, 0x77, 0x41, 0x16, 0x28, 0x8f,
	0x1d, 0xbb, 0xce, 0xa5, 0xca, 0xcf, 0xb1, 0xe9, 0xd8, 0x32, 0xe7, 0x84, 0x5d, 0xd9, 0xd4, 0x4a,
	0x25, 0xee, 0xba, 0x26, 0xa6, 0x17, 0xee, 0xc5, 0x57, 0x8e, 0xa7, 0x8b, 0xf1, 0x0b, 0xbb, 0x72,
	0xb7, 0x16, 0x73, 0x1d, 0xec, 0x12, 0x7b, 0x6c, 0x3b, 0x78, 0x4e, 0xe2, 0x63, 0x36, 0xf3, 0xe2,
	0x6b, 0x06, 0x72, 0x86, 0x3d, 0x6b, 0x99, 0x33, 0x3c, 0x9f, 0xa0, 0xbf, 0x21, 0x3f, 0xa1, 0xa3,
	0x21, 0x59, 0x39, 0x66, 0x39, 0x51, 0x4d, 0xd4, 0x0e, 0xaf, 0xcf, 0xea, 0xb1, 0x2d, 0xd7, 0xd9,
	0xcc, 0xc1, 0xca, 0x31, 0x75, 0x98, 0x84, 0x63, 0x7f, 0xa5, 0x47, 0x30, 0x59, 0x7a, 0x6c, 0x65,
	0x52, 0xb1, 0xd2, 0xa0, 0x3e, 0x5b, 0xe9, 0x85, 0x63, 0x84, 0x20, 0x35, 0x33, 0x09, 0x2e, 0xef,
	0x56, 0x13, 0xb5, 0x9c, 0x4e, 0xc7, 0xe8, 0x16, 0x8e, 0x2c, 0x93, 0x0c, 0x69, 0x31, 0xbc, 0x21,
	0xbb, 0x4d, 0x39, 0x55, 0x4d, 0xd4, 0xf2, 0xd7, 0x15, 0xca, 0x64, 0x65, 0xea, 0x98, 0x44, 0xa3,
	0x53, 0xd8, 0xa6, 0x6e, 0x77, 0xf4, 0x82, 0x25, 0x4a, 0x3e, 0xc9, 0x93, 0x48, 0x7b, 0x12, 0xc9,
	0x90, 0x49, 0xde, 0x1a, 0xe9, 0x11, 0x4e, 0xc3, 0x3d, 0x0d, 0xdd, 0xc5, 0x92, 0x98, 0x01, 0x2e,
	0x4d, 0x71, 0xbf, 0x2a, 0x36, 0xa6, 0xfb, 0xd3, 0x42, 0xe4, 0xb1, 0x25, 0xcb, 0xe8, 0x0d, 0x9c,
	0xc5, 0x1e, 0x55, 0xe0, 0x66, 0x28, 0xf7, 0x37, 0xd5, 0x03, 0x8b, 0xe0, 0x92, 0xa5, 0xd0, 0x91,
	0x06, 0x05, 0x4a, 0x76, 0x4d, 0x1c, 0x10, 0xb3, 0x94, 0xc8, 0x5e, 0x0b, 0x3d, 0x4c, 0x3e, 0xd0,
	0x35, 0x71, 0x48, 0x3a, 0xb0, 0xe2, 0x02, 0x7a, 0xcf, 0x9e, 0x39, 0x76, 0x6c, 0x02, 0x52, 0x8e,
	0x92, 0x7e, 0xa7, 0xa4, 0xf8, 0xa9, 0xea, 0x98, 0xa4, 0x1f, 0xfd, 0x29, 0xec, 0x50, 0xd2, 0x7d,
	0xbc, 0xa7, 0xc6, 0xc3, 0x06, 0xbc, 0xb1, 0x01, 0xef, 0xa9, 0xf0, 0x6d, 0x28, 0xfa, 0x78, 0xda,
	0x18, 0x01, 0x38, 0x4f, 0xc1, 0xe7, 0x14, 0xcc, 0x3a, 0xc6, 0x30, 0x49, 0xd3, 0x1f, 0x84, 0xb0,
	0x43, 0x4f, 0x50, 0xd0, 0x7f, 0x50, 0x7a, 0x5a, 0xb8, 0x1f, 0xb0, 0x3b, 0x11, 0x51, 0xfb, 0x14,
	0xf5, 0x4b, 0x0c, 0x75, 0xc3, 0xa6, 0x89, 0x38, 0xf4, 0x24, 0xa9, 0xfe, 0xa9, 0x1c, 0xe1, 0xf1,
	0x8b, 0xc8, 0x3b, 0x88, 0x9d, 0x4a, 0xc6, 0x6b, 0xe0, 0xf1, 0x8b, 0x08, 0x2b, 0x8c, 0x44, 0xa9,
	0x91, 0x86, 0xd4, 0x04, 0x13, 0x7c, 0xf1, 0x39, 0x4b, 0xfb, 0xd8, 0x58, 0x3a, 0xce, 0x74, 0x45,
	0xbb, 0x91, 0x8e, 0x36, 0xf7, 0x31, 0x9b, 0xc9, 0xbb, 0x31, 0x1c, 0xff, 0xd0, 0x3e, 0x66, 0xb7,
	0xd9, 0xd6, 0xc7, 0x6c, 0x53, 0x42, 0x1f, 0xf3, 0x27, 0x12, 0xfb, 0x98, 0x93, 0xb6, 0xf4, 0x71,
	0x44, 0xf2, 0xd6, 0x48, 0x03, 0x38, 0x09, 0x5e, 0xa7, 0x48, 0x93, 0xdb, 0x98, 0xbf, 0xcf, 0x35,
	0xe2, 0xf1, 0x93, 0x2c, 0xab, 0xd2, 0x81, 0x63, 0x33, 0xdb, 0xd3, 0x21, 0xc2, 0x5a, 0xb2, 0xac,
	0x4c, 0x07, 0xce, 0xcd, 0x7e, 0x27, 0x1d, 0x42, 0xf0, 0x5a, 0x3a, 0x70, 0x72, 0x3c, 0x1d, 0x38,
	0x31, 0xb7, 0x21, 0x1d, 0x42, 0x52, 0x90, 0x0e, 0x1c, 0xa1, 0x48, 0x07, 0x4e, 0x82, 0x57, 0xa5,
	0x83, 0xb0, 0x43, 0x49, 0x57, 0xa5, 0x03, 0xc7, 0xe7, 0x5f, 0x95, 0x0e, 0x11, 0xde, 0x53, 0xe1,
	0x85, 0x74, 0xe0, 0xe0, 0xfd, 0x8d, 0xe9, 0x10, 0xc2, 0xc2, 0x74, 0xe0, 0x18, 0x29, 0x1d, 0x38,
	0xea, 0x60, 0x6b, 0x3a, 0x84, 0x38, 0x21, 0x1d, 0xa2, 0xb3, 0x1e, 0x4b, 0x07, 0xce, 0x3b, 0xdc,
	0x9c, 0x0e, 0xd1, 0x59, 0x1f, 0x89, 0x52, 0x90, 0x0e, 0x97, 0x7f, 0x00, 0x44, 0x5d, 0x8b, 0xd2,
	0x90, 0xec, 0xdd, 0x17, 0x77, 0xfc, 0xdf, 0x6e, 0xa7, 0x98, 0x40, 0x59, 0x48, 0x75, 0x7b, 0xdd,
	0x76, 0x31, 0x79, 0xf9, 0x29, 0x09, 0x10, 0xfd, 0x83, 0x47, 0x27, 0x70, 0xd4, 0x69, 0x0f, 0x86,
	0x5a, 0xa7, 0xdd, 0x1d, 0x18, 0xc3, 0x56, 0xfb, 0x5f, 0xad, 0xdb, 0x2a, 0xee, 0xf8, 0xb2, 0x21,
	0xc9, 0x09, 0xf4, 0x13, 0x9c, 0xc5, 0x66, 0xeb, 0xbd, 0xc7, 0x41, 0x3b, 0x30, 0x93, 0xbe, 0x69,
	0x6c, 0x30, 0x77, 0xd1, 0x31, 0x14, 0xe8, 0x4a, 0xbd, 0xad, 0x05, 0x62, 0x0a, 0x55, 0xe0, 0xd4,
	0x17, 0xfb, 0x9a, 0x3e, 0xb8, 0x6b, 0xde, 0xf5, 0xb5, 0xee, 0x20, 0xf0, 0xf6, 0x7c, 0xcf, 0x50,
	0x7b, 0x69, 0x54, 0x82, 0xa2, 0xef, 0x35, 0x1f, 0x7a, 0xcd, 0xfb, 0x40, 0xcd, 0xa0, 0x32, 0x94,
	0x6e, 0x7a, 0xfa, 0xff, 0x9a, 0xde, 0x12, 0x9d, 0xac, 0xff, 0x34, 0x0d, 0xad, 0x79, 0x2f, 0xca,
	0xb9, 0xcb, 0x2f, 0x49, 0x80, 0x28, 0x23, 0xd7, 0x4a, 0x61, 0x3c, 0xf6, 0xfb, 0x0f, 0x6f, 0xa5,
	0x52, 0x70, 0x39, 0x81, 0xce, 0xe1, 0x24, 0xb8, 0x9b, 0x68, 0x25, 0x95, 0x55, 0xe2, 0xe6, 0xae,
	0xb2, 0x4a, 0xdc, 0x4c, 0x09, 0x55, 0xe2, 0xe2, 0x9e, 0xaa, 0x4a, 0xdc, 0x4b, 0xab, 0xaa, 0xc4,
	0xbd, 0x8c, 0x58, 0x25, 0xae, 0x66, 0xe5, 0x2a, 0x71, 0x27, 0xb7, 0x56, 0x25, 0x2e, 0x43, 0xe3,
	0x9f, 0x77, 0x7f, 0x59, 0x36, 0x79, 0x5e, 0x8e, 0xea, 0xe3, 0xc5, 0x6c, 0xfd, 0x8b, 0x77, 0x88,
	0xa7, 0xce, 0x33, 0xbe, 0xc2, 0x8e, 0x7d, 0x25, 0x7f, 0x16, 0x8f, 0xd2, 0xf4, 0x03, 0xf4, 0xcf,
	0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xcf, 0xcf, 0x56, 0x33, 0x0b, 0x00, 0x00,
}
