# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routing/routing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='routing/routing.proto',
  package='api.routing',
  syntax='proto3',
  serialized_options=_b('Z,github.com/synerex/synerex_alpha/api/routing'),
  serialized_pb=_b('\n\x15routing/routing.proto\x12\x0b\x61pi.routing\x1a\x1egoogle/protobuf/duration.proto\x1a\x13\x63ommon/common.proto\"\xc7\x02\n\x0eRoutingService\x12\x13\n\x0boperator_id\x18\x01 \x01(\x05\x12\'\n\x0c\x64\x65part_place\x18\x04 \x01(\x0b\x32\x11.api.common.Place\x12\'\n\x0c\x61rrive_place\x18\x05 \x01(\x0b\x32\x11.api.common.Place\x12%\n\x0b\x64\x65part_time\x18\x06 \x01(\x0b\x32\x10.api.common.Time\x12%\n\x0b\x61rrive_time\x18\x07 \x01(\x0b\x32\x10.api.common.Time\x12.\n\x0b\x61mount_time\x18\x08 \x01(\x0b\x32\x19.google.protobuf.Duration\x12-\n\ndelay_time\x18\r \x01(\x0b\x32\x19.google.protobuf.Duration\x12!\n\x06points\x18\x0f \x03(\x0b\x32\x11.api.common.PointB.Z,github.com/synerex/synerex_alpha/api/routingb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,common_dot_common__pb2.DESCRIPTOR,])




_ROUTINGSERVICE = _descriptor.Descriptor(
  name='RoutingService',
  full_name='api.routing.RoutingService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator_id', full_name='api.routing.RoutingService.operator_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depart_place', full_name='api.routing.RoutingService.depart_place', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_place', full_name='api.routing.RoutingService.arrive_place', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depart_time', full_name='api.routing.RoutingService.depart_time', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrive_time', full_name='api.routing.RoutingService.arrive_time', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_time', full_name='api.routing.RoutingService.amount_time', index=5,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay_time', full_name='api.routing.RoutingService.delay_time', index=6,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='api.routing.RoutingService.points', index=7,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=419,
)

_ROUTINGSERVICE.fields_by_name['depart_place'].message_type = common_dot_common__pb2._PLACE
_ROUTINGSERVICE.fields_by_name['arrive_place'].message_type = common_dot_common__pb2._PLACE
_ROUTINGSERVICE.fields_by_name['depart_time'].message_type = common_dot_common__pb2._TIME
_ROUTINGSERVICE.fields_by_name['arrive_time'].message_type = common_dot_common__pb2._TIME
_ROUTINGSERVICE.fields_by_name['amount_time'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_ROUTINGSERVICE.fields_by_name['delay_time'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_ROUTINGSERVICE.fields_by_name['points'].message_type = common_dot_common__pb2._POINT
DESCRIPTOR.message_types_by_name['RoutingService'] = _ROUTINGSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoutingService = _reflection.GeneratedProtocolMessageType('RoutingService', (_message.Message,), {
  'DESCRIPTOR' : _ROUTINGSERVICE,
  '__module__' : 'routing.routing_pb2'
  # @@protoc_insertion_point(class_scope:api.routing.RoutingService)
  })
_sym_db.RegisterMessage(RoutingService)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
