// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/area/area.proto

package area

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/synerex/synerex_alpha/api/simulation/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAreaRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAreaRequest) Reset()         { *m = GetAreaRequest{} }
func (m *GetAreaRequest) String() string { return proto.CompactTextString(m) }
func (*GetAreaRequest) ProtoMessage()    {}
func (*GetAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8212774c97f163d, []int{0}
}

func (m *GetAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAreaRequest.Unmarshal(m, b)
}
func (m *GetAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAreaRequest.Marshal(b, m, deterministic)
}
func (m *GetAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAreaRequest.Merge(m, src)
}
func (m *GetAreaRequest) XXX_Size() int {
	return xxx_messageInfo_GetAreaRequest.Size(m)
}
func (m *GetAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAreaRequest proto.InternalMessageInfo

func (m *GetAreaRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAreaResponse struct {
	Area                 *Area    `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAreaResponse) Reset()         { *m = GetAreaResponse{} }
func (m *GetAreaResponse) String() string { return proto.CompactTextString(m) }
func (*GetAreaResponse) ProtoMessage()    {}
func (*GetAreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8212774c97f163d, []int{1}
}

func (m *GetAreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAreaResponse.Unmarshal(m, b)
}
func (m *GetAreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAreaResponse.Marshal(b, m, deterministic)
}
func (m *GetAreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAreaResponse.Merge(m, src)
}
func (m *GetAreaResponse) XXX_Size() int {
	return xxx_messageInfo_GetAreaResponse.Size(m)
}
func (m *GetAreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAreaResponse proto.InternalMessageInfo

func (m *GetAreaResponse) GetArea() *Area {
	if m != nil {
		return m.Area
	}
	return nil
}

type Area struct {
	Id                   uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NeighborAreas        []uint64   `protobuf:"varint,3,rep,packed,name=neighbor_areas,json=neighborAreas,proto3" json:"neighbor_areas,omitempty"`
	DuplicateArea        *AreaCoord `protobuf:"bytes,4,opt,name=duplicate_area,json=duplicateArea,proto3" json:"duplicate_area,omitempty"`
	ControlArea          *AreaCoord `protobuf:"bytes,5,opt,name=control_area,json=controlArea,proto3" json:"control_area,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8212774c97f163d, []int{2}
}

func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (m *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(m, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Area) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Area) GetNeighborAreas() []uint64 {
	if m != nil {
		return m.NeighborAreas
	}
	return nil
}

func (m *Area) GetDuplicateArea() *AreaCoord {
	if m != nil {
		return m.DuplicateArea
	}
	return nil
}

func (m *Area) GetControlArea() *AreaCoord {
	if m != nil {
		return m.ControlArea
	}
	return nil
}

type AreaCoord struct {
	StartLat             float64  `protobuf:"fixed64,1,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLon             float64  `protobuf:"fixed64,2,opt,name=start_lon,json=startLon,proto3" json:"start_lon,omitempty"`
	EndLat               float64  `protobuf:"fixed64,3,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLon               float64  `protobuf:"fixed64,4,opt,name=end_lon,json=endLon,proto3" json:"end_lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaCoord) Reset()         { *m = AreaCoord{} }
func (m *AreaCoord) String() string { return proto.CompactTextString(m) }
func (*AreaCoord) ProtoMessage()    {}
func (*AreaCoord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8212774c97f163d, []int{3}
}

func (m *AreaCoord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaCoord.Unmarshal(m, b)
}
func (m *AreaCoord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaCoord.Marshal(b, m, deterministic)
}
func (m *AreaCoord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaCoord.Merge(m, src)
}
func (m *AreaCoord) XXX_Size() int {
	return xxx_messageInfo_AreaCoord.Size(m)
}
func (m *AreaCoord) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaCoord.DiscardUnknown(m)
}

var xxx_messageInfo_AreaCoord proto.InternalMessageInfo

func (m *AreaCoord) GetStartLat() float64 {
	if m != nil {
		return m.StartLat
	}
	return 0
}

func (m *AreaCoord) GetStartLon() float64 {
	if m != nil {
		return m.StartLon
	}
	return 0
}

func (m *AreaCoord) GetEndLat() float64 {
	if m != nil {
		return m.EndLat
	}
	return 0
}

func (m *AreaCoord) GetEndLon() float64 {
	if m != nil {
		return m.EndLon
	}
	return 0
}

type Area2 struct {
	Id                   uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NeighborAreas        []uint64        `protobuf:"varint,3,rep,packed,name=neighbor_areas,json=neighborAreas,proto3" json:"neighbor_areas,omitempty"`
	DuplicateArea        []*common.Coord `protobuf:"bytes,4,rep,name=duplicate_area,json=duplicateArea,proto3" json:"duplicate_area,omitempty"`
	ControlArea          []*common.Coord `protobuf:"bytes,5,rep,name=control_area,json=controlArea,proto3" json:"control_area,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Area2) Reset()         { *m = Area2{} }
func (m *Area2) String() string { return proto.CompactTextString(m) }
func (*Area2) ProtoMessage()    {}
func (*Area2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8212774c97f163d, []int{4}
}

func (m *Area2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area2.Unmarshal(m, b)
}
func (m *Area2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area2.Marshal(b, m, deterministic)
}
func (m *Area2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area2.Merge(m, src)
}
func (m *Area2) XXX_Size() int {
	return xxx_messageInfo_Area2.Size(m)
}
func (m *Area2) XXX_DiscardUnknown() {
	xxx_messageInfo_Area2.DiscardUnknown(m)
}

var xxx_messageInfo_Area2 proto.InternalMessageInfo

func (m *Area2) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Area2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Area2) GetNeighborAreas() []uint64 {
	if m != nil {
		return m.NeighborAreas
	}
	return nil
}

func (m *Area2) GetDuplicateArea() []*common.Coord {
	if m != nil {
		return m.DuplicateArea
	}
	return nil
}

func (m *Area2) GetControlArea() []*common.Coord {
	if m != nil {
		return m.ControlArea
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAreaRequest)(nil), "api.area.GetAreaRequest")
	proto.RegisterType((*GetAreaResponse)(nil), "api.area.GetAreaResponse")
	proto.RegisterType((*Area)(nil), "api.area.Area")
	proto.RegisterType((*AreaCoord)(nil), "api.area.AreaCoord")
	proto.RegisterType((*Area2)(nil), "api.area.Area2")
}

func init() { proto.RegisterFile("simulation/area/area.proto", fileDescriptor_c8212774c97f163d) }

var fileDescriptor_c8212774c97f163d = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0x4d, 0xda, 0x5f, 0xbb, 0xfd, 0x35, 0xe2, 0x7a, 0x30, 0x54, 0x90, 0x10, 0x10, 0x72,
	0x4a, 0xa0, 0xd6, 0x22, 0xde, 0xd4, 0x83, 0x17, 0x4f, 0x39, 0x7a, 0x29, 0xdb, 0x66, 0x69, 0x17,
	0x92, 0x9d, 0xb8, 0xbb, 0x41, 0xfd, 0x7a, 0x82, 0xdf, 0x4b, 0x76, 0xda, 0x84, 0x5a, 0xdb, 0x9b,
	0x97, 0x6c, 0x66, 0xde, 0x7b, 0xf3, 0xe7, 0x31, 0x64, 0xac, 0x45, 0x59, 0x17, 0xcc, 0x08, 0x90,
	0x29, 0x53, 0x9c, 0xe1, 0x27, 0xa9, 0x14, 0x18, 0xa0, 0x7d, 0x56, 0x89, 0xc4, 0xc6, 0xe3, 0xcb,
	0x1d, 0xd6, 0x12, 0xca, 0xb2, 0x7d, 0x36, 0xcc, 0x28, 0x24, 0xfe, 0x13, 0x37, 0xf7, 0x8a, 0xb3,
	0x8c, 0xbf, 0xd6, 0x5c, 0x1b, 0xea, 0x93, 0x8e, 0xc8, 0x03, 0x27, 0x74, 0x62, 0x2f, 0xeb, 0x88,
	0x3c, 0xba, 0x21, 0x27, 0x2d, 0x43, 0x57, 0x20, 0x35, 0xa7, 0x11, 0xf1, 0x6c, 0x71, 0x24, 0x0d,
	0x27, 0x7e, 0xd2, 0x74, 0x4b, 0x90, 0x85, 0x58, 0xf4, 0xe5, 0x10, 0xcf, 0x86, 0xfb, 0xf5, 0x28,
	0x25, 0x9e, 0x64, 0x25, 0x0f, 0x3a, 0xa1, 0x13, 0x0f, 0x32, 0xfc, 0xa7, 0x57, 0xc4, 0x97, 0x5c,
	0xac, 0xd6, 0x0b, 0x50, 0x73, 0xab, 0xd6, 0x81, 0x1b, 0xba, 0xb1, 0x97, 0x8d, 0x9a, 0xac, 0xad,
	0xa4, 0xe9, 0x1d, 0xf1, 0xf3, 0xba, 0x2a, 0xc4, 0x92, 0x19, 0x8e, 0xbc, 0xc0, 0xc3, 0x09, 0xce,
	0x7e, 0x4e, 0xf0, 0x08, 0xa0, 0xf2, 0x6c, 0xd4, 0x52, 0x71, 0x8c, 0x19, 0xf9, 0xbf, 0x04, 0x69,
	0x14, 0x14, 0x1b, 0x65, 0xf7, 0xb8, 0x72, 0xb8, 0x25, 0xda, 0x4c, 0xf4, 0x46, 0x06, 0x2d, 0x42,
	0x2f, 0xc8, 0x40, 0x1b, 0xa6, 0xcc, 0xbc, 0x60, 0x06, 0x57, 0x72, 0xb2, 0x3e, 0x26, 0x9e, 0x99,
	0xd9, 0x01, 0x41, 0xe2, 0x76, 0x2d, 0x08, 0x92, 0x9e, 0x93, 0x7f, 0x5c, 0xe6, 0xa8, 0x73, 0x11,
	0xea, 0x71, 0x99, 0x5b, 0x55, 0x03, 0x80, 0xc4, 0x65, 0xb6, 0x00, 0xc8, 0xe8, 0xd3, 0x21, 0x5d,
	0xdb, 0x79, 0xf2, 0x97, 0x0e, 0xde, 0x1e, 0x70, 0xd0, 0x8d, 0x87, 0x93, 0x53, 0xf4, 0x61, 0x7b,
	0x19, 0x07, 0xfd, 0x9b, 0xfe, 0xf2, 0xef, 0x88, 0x6e, 0xd7, 0xbd, 0x87, 0xd9, 0xcb, 0x74, 0x25,
	0xcc, 0xba, 0x5e, 0x58, 0x4e, 0xaa, 0x3f, 0x24, 0x57, 0xfc, 0xbd, 0x79, 0xe7, 0xac, 0xa8, 0xd6,
	0x2c, 0x65, 0x95, 0x48, 0xf7, 0x6e, 0x79, 0xd1, 0xc3, 0xeb, 0xbc, 0xfe, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0x84, 0xe3, 0x9a, 0x0a, 0xe5, 0x02, 0x00, 0x00,
}
