// Code generated by protoc-gen-go. DO NOT EDIT.
// source: area/area.proto

package area

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AreaService struct {
	AreaId               uint32             `protobuf:"varint,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	AreaName             string             `protobuf:"bytes,2,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	Coord                *AreaService_Coord `protobuf:"bytes,3,opt,name=coord,proto3" json:"coord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AreaService) Reset()         { *m = AreaService{} }
func (m *AreaService) String() string { return proto.CompactTextString(m) }
func (*AreaService) ProtoMessage()    {}
func (*AreaService) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf477ccdfe50b7a, []int{0}
}

func (m *AreaService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaService.Unmarshal(m, b)
}
func (m *AreaService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaService.Marshal(b, m, deterministic)
}
func (m *AreaService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaService.Merge(m, src)
}
func (m *AreaService) XXX_Size() int {
	return xxx_messageInfo_AreaService.Size(m)
}
func (m *AreaService) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaService.DiscardUnknown(m)
}

var xxx_messageInfo_AreaService proto.InternalMessageInfo

func (m *AreaService) GetAreaId() uint32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *AreaService) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

func (m *AreaService) GetCoord() *AreaService_Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type AreaService_Coord struct {
	SLat                 float32  `protobuf:"fixed32,1,opt,name=s_lat,json=sLat,proto3" json:"s_lat,omitempty"`
	SLon                 float32  `protobuf:"fixed32,2,opt,name=s_lon,json=sLon,proto3" json:"s_lon,omitempty"`
	ELat                 float32  `protobuf:"fixed32,3,opt,name=e_lat,json=eLat,proto3" json:"e_lat,omitempty"`
	ELon                 float32  `protobuf:"fixed32,4,opt,name=e_lon,json=eLon,proto3" json:"e_lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaService_Coord) Reset()         { *m = AreaService_Coord{} }
func (m *AreaService_Coord) String() string { return proto.CompactTextString(m) }
func (*AreaService_Coord) ProtoMessage()    {}
func (*AreaService_Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf477ccdfe50b7a, []int{0, 0}
}

func (m *AreaService_Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaService_Coord.Unmarshal(m, b)
}
func (m *AreaService_Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaService_Coord.Marshal(b, m, deterministic)
}
func (m *AreaService_Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaService_Coord.Merge(m, src)
}
func (m *AreaService_Coord) XXX_Size() int {
	return xxx_messageInfo_AreaService_Coord.Size(m)
}
func (m *AreaService_Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaService_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_AreaService_Coord proto.InternalMessageInfo

func (m *AreaService_Coord) GetSLat() float32 {
	if m != nil {
		return m.SLat
	}
	return 0
}

func (m *AreaService_Coord) GetSLon() float32 {
	if m != nil {
		return m.SLon
	}
	return 0
}

func (m *AreaService_Coord) GetELat() float32 {
	if m != nil {
		return m.ELat
	}
	return 0
}

func (m *AreaService_Coord) GetELon() float32 {
	if m != nil {
		return m.ELon
	}
	return 0
}

func init() {
	proto.RegisterType((*AreaService)(nil), "api.area.AreaService")
	proto.RegisterType((*AreaService_Coord)(nil), "api.area.AreaService.Coord")
}

func init() { proto.RegisterFile("area/area.proto", fileDescriptor_6bf477ccdfe50b7a) }

var fileDescriptor_6bf477ccdfe50b7a = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xc9, 0xee, 0x76, 0xdd, 0xcd, 0x22, 0x42, 0x3c, 0x58, 0xdc, 0x4b, 0xf1, 0x54, 0x11,
	0x52, 0xd4, 0x27, 0x50, 0x4f, 0x82, 0x78, 0x88, 0x37, 0x3d, 0x94, 0xd9, 0x76, 0x70, 0x03, 0xdb,
	0x4c, 0x48, 0xa3, 0xe8, 0x73, 0xfa, 0x42, 0x92, 0x69, 0x0b, 0x7b, 0x49, 0xf8, 0xbf, 0xf9, 0x98,
	0x81, 0x5f, 0x9e, 0x41, 0x40, 0xa8, 0xd2, 0xa3, 0x7d, 0xa0, 0x48, 0x6a, 0x05, 0xde, 0xea, 0x94,
	0xaf, 0xfe, 0x84, 0xdc, 0x3c, 0x04, 0x84, 0x37, 0x0c, 0xdf, 0xb6, 0x41, 0x75, 0x21, 0x4f, 0x12,
	0xaf, 0x6d, 0x9b, 0x8b, 0x42, 0x94, 0xa7, 0x66, 0x99, 0xe2, 0x73, 0xab, 0xb6, 0x72, 0xcd, 0x03,
	0x07, 0x1d, 0xe6, 0xb3, 0x42, 0x94, 0x6b, 0xb3, 0x4a, 0xe0, 0x15, 0x3a, 0x54, 0xb7, 0x32, 0x6b,
	0x88, 0x42, 0x9b, 0xcf, 0x0b, 0x51, 0x6e, 0xee, 0xb6, 0x7a, 0xda, 0xaf, 0x8f, 0x76, 0xeb, 0xa7,
	0xa4, 0x98, 0xc1, 0xbc, 0xfc, 0x90, 0x19, 0x67, 0x75, 0x2e, 0xb3, 0xbe, 0x3e, 0x40, 0xe4, 0x7b,
	0x33, 0xb3, 0xe8, 0x5f, 0x20, 0x8e, 0x90, 0x1c, 0x5f, 0x62, 0x48, 0x2e, 0x41, 0x64, 0x73, 0x3e,
	0x40, 0x1c, 0x4d, 0x64, 0x73, 0x31, 0x41, 0x72, 0x8f, 0x37, 0xef, 0xd7, 0x9f, 0x36, 0xee, 0xbf,
	0x76, 0xba, 0xa1, 0xae, 0xea, 0x7f, 0x1d, 0x06, 0xfc, 0x99, 0xfe, 0x1a, 0x0e, 0x7e, 0x0f, 0x15,
	0x78, 0xcb, 0x95, 0xec, 0x96, 0xdc, 0xc9, 0xfd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x6d,
	0x2b, 0x2e, 0x26, 0x01, 0x00, 0x00,
}
